import { useEffect, useRef, useState } from 'react';
import { Dropzone } from '../character/Dropzone';
import { SketchRig } from '../character/SketchRig';
import { SkeletonTree } from '../skeleton/SkeletonTree';
import { ViewportCanvas } from '../viewport/ViewportCanvas';
import { ViewportHUD } from '../viewport/ViewportHUD';
import { ScrubApplier } from '../viewport/PlaybackEngine';
import { BoneDetails } from '../inspector/BoneDetails';
import { ThemePanel } from '../inspector/ThemePanel';
import { RenderPanel } from '../inspector/RenderPanel';
import { FacePanel } from '../inspector/FacePanel';
import { AppearancePanel } from '../inspector/AppearancePanel';
import { IdlePanel } from '../ai/IdlePanel';
import { TransformPanel } from '../inspector/TransformPanel';
import { IKPanel } from '../inspector/IKPanel';
import { AutoPosePanel } from '../inspector/AutoPosePanel';
import { CameraPanel } from '../inspector/CameraPanel';
import { StoryboardPanel } from '../inspector/StoryboardPanel';
import { ActionPlanPanel } from '../inspector/ActionPlanPanel';
import { StagePanel } from '../inspector/StagePanel';
import { EffectsPanel } from '../inspector/EffectsPanel';
import { Timeline } from '../timeline/Timeline';
import { ActionPresets } from '../ai/ActionPresets';
import { MotionLibraryPanel } from '../ai/MotionLibraryPanel';
import { MotionPanel } from '../ai/MotionPanel';
import { InbetweenPanel } from '../ai/InbetweenPanel';
import { PhysicsPanel } from '../ai/PhysicsPanel';
import { AgentPanel } from '../ai/AgentPanel';
import { ProviderBadge } from '../ai/ProviderBadge';
import { useAnimationStore } from '../../stores/animationStore';
import { useHistoryStore } from '../../stores/historyStore';
import { useCharacterStore } from '../../stores/characterStore';
import { useSkeletonStore } from '../../stores/skeletonStore';
import { useViewportStore } from '../../stores/viewportStore';
import { useCameraStore } from '../../stores/cameraStore';
import { usePrevisStore } from '../../stores/previsStore';
import { useWorldStore } from '../../stores/worldStore';
import { useEffectsStore } from '../../stores/effectsStore';
import { parseProjectFile, serializeProject } from '../../core/project/serialize';
import type { ProjectV1 } from '../../core/project/schema';
import { rebuildSketchCharacter } from '../../services/sketch/buildSketchCharacter';
import { activateCharacter, deactivateCharacter, reconcileProjectCharacter } from '../character/activateCharacter';
import { resetSidebarScroll } from './mobileSidebar';
import { useSketchStore } from '../../stores/sketchStore';

function downloadText(name: string, text: string) {
  const blob = new Blob([text], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

function ToolbarActions() {
  const undo = useAnimationStore((s) => s.undo);
  const redo = useAnimationStore((s) => s.redo);
  const pastLen = useHistoryStore((s) => s.past.length);
  const futureLen = useHistoryStore((s) => s.future.length);
  const openRef = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);

  const doNew = () => {
    useAnimationStore.getState().clearProject();
    useCameraStore.getState().clear();
    usePrevisStore.getState().clear();
    useWorldStore.getState().clear();
    useEffectsStore.getState().clear();
    useSketchStore.getState().restoreDraft(null);
    setMsg('已新建空项目（角色保留）');
  };

  const doSave = () => {
    const anim = useAnimationStore.getState();
    const cameraState = useCameraStore.getState();
    usePrevisStore.getState().syncEditorContext(
      useWorldStore.getState().props,
      useEffectsStore.getState().events,
      cameraState.keyframes,
      Object.fromEntries(anim.animations.map((animation) => [animation.id, animation.duration])),
      anim.activeId,
      cameraState.enabled,
      cameraState.autoGenerated,
    );
    const project: ProjectV1 = {
      version: '1.0',
      character: useCharacterStore.getState().meta,
      sketchDraft: useSketchStore.getState().draft,
      skeleton: useSkeletonStore.getState().snapshot,
      animations: anim.animations,
      activeAnimationId: anim.activeId,
      previs: usePrevisStore.getState().byAnimationId,
      scene: {
        bg: '#0b0d12',
        grid: useViewportStore.getState().showGrid,
        shadows: useViewportStore.getState().shadows,
        props: useWorldStore.getState().props,
        effects: useEffectsStore.getState().events,
      },
      camera: {
        position: [2.5, 1.8, 3.2], target: [0, 1, 0], fov: 45,
        keyframes: useCameraStore.getState().keyframes,
        enabled: useCameraStore.getState().enabled,
        autoGenerated: useCameraStore.getState().autoGenerated,
      },
      settings: { fps: 30, loop: anim.loop },
    };
    downloadText('project.json', serializeProject(project));
    setMsg(`已保存 project.json（${project.animations.length} 个动画）`);
  };

  const doOpen = async (f: File) => {
    setBusy(true);
    try {
      const { project, warnings } = parseProjectFile(await f.text());
      useSketchStore.getState().restoreDraft(project.sketchDraft ?? null);
      usePrevisStore.getState().replaceAll(project.previs ?? {});
      const activeAnimationId = project.activeAnimationId ?? project.animations[0]?.id ?? null;
      useAnimationStore.getState().replaceAll(project.animations, activeAnimationId);
      useViewportStore.setState({ showGrid: project.scene.grid, shadows: project.scene.shadows });
      useWorldStore.getState().replaceProps(project.scene.props ?? []);
      useEffectsStore.getState().replace(project.scene.effects ?? []);
      useAnimationStore.setState({ loop: project.settings.loop });
      const activePlanCamera = activeAnimationId ? project.previs?.[activeAnimationId]?.scenePlan?.camera : undefined;
      useCameraStore.getState().activateAnimation(activeAnimationId, activePlanCamera ?? {
        keyframes: project.camera.keyframes ?? [],
        enabled: project.camera.enabled ?? false,
        autoGenerated: project.camera.autoGenerated ?? false,
      }, project.animations.find((animation) => animation.id === activeAnimationId)?.duration ?? 4);
      const bind = reconcileProjectCharacter(project.character, useCharacterStore.getState().meta, {
        clear: deactivateCharacter,
        rebuildSketch: (meta) => {
          const rebuilt = rebuildSketchCharacter(meta);
          activateCharacter(rebuilt.meta, rebuilt.scene, rebuilt.dispose);
        },
      });
      const parts = [`已打开 ${f.name}（${project.animations.length} 个动画）`];
      if (bind === 'match' || bind === 'sketch-restored') parts.push('角色匹配');
      else if (project.character) parts.push(`请拖入原角色 ${project.character.fileName} 后应用动画`);
      else parts.push('项目无角色记录，直接拖入 GLB 即可');
      parts.push(...warnings);
      setMsg(parts.join('；'));
    } catch (e) {
      setMsg(e instanceof Error ? e.message : '打开失败');
    } finally {
      setBusy(false);
    }
  };

  const doExport = async () => {
    const so = useCharacterStore.getState().sceneObject;
    const meta = useCharacterStore.getState().meta;
    const anims = useAnimationStore.getState().animations;
    if (!so || !meta) {
      setMsg('请先加载角色再导出');
      return;
    }
    setBusy(true);
    try {
      const { exportGltf } = await import('../../services/export/exportGltf');
      const r = await exportGltf(so, anims, meta.fileName);
      setMsg([`已导出 ${r.fileName}（${r.clipCount} 个 clip，可拖回验证）`, ...r.warnings].join('；'));
    } catch (e) {
      setMsg(e instanceof Error ? e.message : '导出失败');
    } finally {
      setBusy(false);
    }
  };

  const btn = 'rounded bg-zinc-200 px-2 py-1 hover:bg-zinc-200 disabled:opacity-50';
  return (
    <div className="editor-toolbar-actions ml-auto flex min-w-0 items-center gap-1 text-xs">
      {msg && <span className="mr-1 max-w-72 truncate text-zinc-600" title={msg}>{msg}</span>}
      <button onClick={doNew} className={btn}>New</button>
      <button onClick={() => openRef.current?.click()} disabled={busy} className={btn}>Open</button>
      <input ref={openRef} type="file" accept=".json,application/json" className="hidden" onChange={(e) => {
        const f = e.target.files?.[0];
        if (f) void doOpen(f);
        e.target.value = '';
      }} />
      <button onClick={doSave} className={btn}>Save</button>
      <button onClick={() => void doExport()} disabled={busy} className={btn}>Export</button>
      <button onClick={undo} disabled={pastLen === 0} title="撤销" className={btn}>Undo</button>
      <button onClick={redo} disabled={futureLen === 0} title="重做" className={btn}>Redo</button>
    </div>
  );
}

export function EditorShell() {
  // Inspector stays floating on desktop and becomes a docked workspace on narrow screens.
  const [inspectorOpen, setInspectorOpen] = useState(true);
  const [inspectorTab, setInspectorTab] = useState<'previs' | 'scene' | 'character' | 'display'>('previs');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const sidebarRef = useRef<HTMLElement>(null);
  const stageProps = useWorldStore((state) => state.props);
  const effects = useEffectsStore((state) => state.events);
  const cameraKeyframes = useCameraStore((state) => state.keyframes);
  const cameraEnabled = useCameraStore((state) => state.enabled);
  const cameraAutoGenerated = useCameraStore((state) => state.autoGenerated);
  const activeAnimationId = useAnimationStore((state) => state.activeId);
  const animations = useAnimationStore((state) => state.animations);
  useEffect(() => {
    usePrevisStore.getState().syncEditorContext(stageProps, effects, cameraKeyframes, Object.fromEntries(animations.map((animation) => [animation.id, animation.duration])), activeAnimationId, cameraEnabled, cameraAutoGenerated);
  }, [stageProps, effects, cameraKeyframes, animations, activeAnimationId, cameraEnabled, cameraAutoGenerated]);
  // 全局快捷键：空格=播放/暂停，Ctrl+Z=撤销，Ctrl+Y/Ctrl+Shift+Z=重做（输入框内不触发）
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const el = e.target as HTMLElement | null;
      if (el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT' || el.isContentEditable)) return;
      const anim = useAnimationStore.getState();
      if (e.code === 'Space') {
        e.preventDefault();
        if (anim.active()) anim.setPlaying(!anim.playing);
      } else if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') {
        e.preventDefault();
        if (e.shiftKey) anim.redo();
        else anim.undo();
      } else if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'y') {
        e.preventDefault();
        anim.redo();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  return (
    <div className="editor-shell flex h-full min-h-0 flex-col overflow-hidden bg-[#f5f5f7] text-zinc-800">
      <ScrubApplier />
      {/* Toolbar */}
      <header className="editor-toolbar flex items-center gap-2 border-b border-zinc-200 bg-white/90 px-4 py-2.5">
        <span className="truncate text-sm font-semibold tracking-tight text-zinc-900">AI 3D · 预演工作台</span>
        <ProviderBadge source="real" label="P10 Agent" />
        <ToolbarActions />
      </header>

      {/* AI 命令条（顶部） */}
      <AgentPanel />

      {/* Main */}
      <div className="editor-main-layout relative flex min-h-0 flex-1 overflow-hidden">
        {/* Left */}
        <aside ref={sidebarRef} id="character-tools" className={`editor-sidebar ${sidebarOpen ? 'is-open' : ''} flex w-[clamp(13rem,18vw,17rem)] shrink-0 flex-col overflow-y-auto border-r border-zinc-200/80 bg-white`}>
          <button className="mobile-sidebar-close" onClick={() => setSidebarOpen(false)} aria-label="关闭角色面板">✕</button>
          <div className="border-b border-zinc-200 p-2">
            <Dropzone compact />
          </div>
          <SketchRig />
          <div className="border-b border-zinc-200 px-3 py-1.5 text-xs font-bold text-zinc-600">Skeleton Explorer</div>
          <div className="min-h-0 flex-1">
            <SkeletonTree />
          </div>
        </aside>

        <button
          className="mobile-sidebar-toggle"
          onClick={() => {
            if (!sidebarOpen && sidebarRef.current) resetSidebarScroll(sidebarRef.current);
            setSidebarOpen((open) => !open);
          }}
          aria-expanded={sidebarOpen}
          aria-controls="character-tools"
        >
          人物与骨架
        </button>

        {/* Viewport */}
        <main className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
          <ViewportHUD />
          <div className="min-h-0 flex-1">
            <ViewportCanvas />
          </div>
          <Timeline />
        </main>

        {/* Right：悬浮 Inspector */}
        {inspectorOpen ? (
          <aside className="editor-inspector absolute top-2 right-2 bottom-2 z-20 flex w-[clamp(18rem,25vw,22rem)] flex-col overflow-hidden rounded-2xl border border-white/80 bg-white/90 shadow-[0_18px_60px_-24px_rgba(15,23,42,.28)] backdrop-blur-xl">
            <div className="sticky top-0 z-10 border-b border-zinc-200 bg-white/95 backdrop-blur-xl">
              <div className="flex items-center px-3 py-2 text-xs font-bold text-zinc-600">
                Inspector
                <button onClick={() => setInspectorOpen(false)} title="关闭面板（视口右上可重新打开）" className="ml-auto rounded px-1.5 py-0.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700">
                ✕
                </button>
              </div>
              <div className="editor-inspector-tabs" role="tablist" aria-label="工作区">
                {([
                  ['previs', '预演'], ['scene', '场景'], ['character', '角色'], ['display', '显示'],
                ] as const).map(([id, label]) => <button
                  key={id}
                  role="tab"
                  aria-selected={inspectorTab === id}
                  aria-controls={`inspector-panel-${id}`}
                  onClick={() => setInspectorTab(id)}
                  className={inspectorTab === id ? 'is-active' : ''}
                >{label}</button>)}
              </div>
            </div>
            <div className="min-h-0 flex-1 overflow-auto">
              <div id="inspector-panel-previs" role="tabpanel" aria-label="预演" hidden={inspectorTab !== 'previs'}>
                <ActionPresets />
                <MotionLibraryPanel />
                <ActionPlanPanel />
                <MotionPanel />
                <InbetweenPanel />
                <PhysicsPanel />
              </div>
              <div id="inspector-panel-scene" role="tabpanel" aria-label="场景与镜头" hidden={inspectorTab !== 'scene'}>
                <StagePanel />
                <CameraPanel />
                <EffectsPanel />
                <StoryboardPanel />
              </div>
              <div id="inspector-panel-character" role="tabpanel" aria-label="角色" hidden={inspectorTab !== 'character'}>
                <ThemePanel />
                <AppearancePanel />
                <FacePanel />
                <IdlePanel />
                <TransformPanel />
                <IKPanel />
                <AutoPosePanel />
                <BoneDetails />
              </div>
              <div id="inspector-panel-display" role="tabpanel" aria-label="显示" hidden={inspectorTab !== 'display'}>
                <RenderPanel />
              </div>
            </div>
          </aside>
        ) : (
          <button
            onClick={() => setInspectorOpen(true)}
            title="打开 Inspector"
            className="editor-inspector-toggle absolute top-2 right-2 z-20 rounded-lg border border-zinc-200 bg-white px-2.5 py-1.5 text-xs text-zinc-600 shadow-lg hover:bg-zinc-50"
          >
            🛠 Inspector
          </button>
        )}
      </div>

      {/* StatusBar */}
      <footer className="flex items-center gap-3 border-t border-zinc-200 bg-white px-3 py-1 text-[11px] text-zinc-500">
        <span>P10: 全功能 REAL（Agent Tool Calling）</span>
        <span>快捷键：空格播放/暂停 · Ctrl+Z 撤销 · Ctrl+Y 重做</span>
      </footer>
    </div>
  );
}
