import { describe, expect, it, beforeEach } from 'vitest';
import { useAnimationStore } from '../src/stores/animationStore';
import { useHistoryStore } from '../src/stores/historyStore';
import { useCameraStore } from '../src/stores/cameraStore';
import { usePrevisStore } from '../src/stores/previsStore';
import { createScenePlan } from '../src/core/previs/scenePlan';

const Q: [number, number, number, number] = [0, 0, 0, 1];

beforeEach(() => {
  useAnimationStore.setState({ animations: [], activeId: null, currentTime: 0, playing: false, loop: true });
  useHistoryStore.getState().clear();
  useCameraStore.getState().activateAnimation(null);
  usePrevisStore.getState().clear();
});

describe('animationStore + history', () => {
  it('打 key → undo 消失 → redo 恢复', () => {
    const st = useAnimationStore.getState();
    const id = st.createAnimation('T');
    useAnimationStore.getState().upsertRotationKey('Hips', 1, Q);
    expect(useAnimationStore.getState().active()?.tracks[0].rotation.length).toBe(1);

    useAnimationStore.getState().undo();
    expect(useAnimationStore.getState().active()?.tracks.length ?? 0).toBe(0);

    useAnimationStore.getState().redo();
    expect(useAnimationStore.getState().active()?.tracks[0].rotation.length).toBe(1);
    expect(useAnimationStore.getState().active()?.id).toBe(id);
  });

  it('删除不存在的 key 不污染 undo 栈', () => {
    useAnimationStore.getState().createAnimation('T');
    const before = useHistoryStore.getState().past.length;
    const ok = useAnimationStore.getState().deleteRotationKey('Hips', 1);
    expect(ok).toBe(false);
    expect(useHistoryStore.getState().past.length).toBe(before);
  });

  it('setDuration 裁掉越界 key', () => {
    useAnimationStore.getState().createAnimation('T');
    useAnimationStore.getState().upsertRotationKey('Hips', 3.5, Q);
    useAnimationStore.getState().setDuration(2);
    expect(useAnimationStore.getState().active()?.duration).toBe(2);
    expect(useAnimationStore.getState().active()?.tracks[0].rotation.length).toBe(0);
  });

  it('允许 0.5 秒时长，并拒绝无效值且不污染 undo 栈', () => {
    useAnimationStore.getState().createAnimation('T');
    useAnimationStore.getState().setDuration(0.5);
    expect(useAnimationStore.getState().active()?.duration).toBe(0.5);
    const historyLength = useHistoryStore.getState().past.length;

    useAnimationStore.getState().setDuration(Number.NaN);
    useAnimationStore.getState().setDuration(0.49);
    useAnimationStore.getState().setDuration(121);

    expect(useAnimationStore.getState().active()?.duration).toBe(0.5);
    expect(useHistoryStore.getState().past.length).toBe(historyLength);
  });

  it('忽略非有限播放时间', () => {
    useAnimationStore.getState().createAnimation('T');
    useAnimationStore.getState().setTime(Number.NaN);
    useAnimationStore.getState().setTime(Number.POSITIVE_INFINITY);
    expect(useAnimationStore.getState().currentTime).toBe(0);
  });

  it('表情关键帧写入、删除和撤销重做共用动画历史', () => {
    useAnimationStore.getState().createAnimation('脸部');
    useAnimationStore.getState().upsertFaceKey('0', 'eyeBlinkLeft', 1, 0.8);
    expect(useAnimationStore.getState().active()?.faceTracks?.[0].keys[0].value).toBe(0.8);
    useAnimationStore.getState().undo();
    expect(useAnimationStore.getState().active()?.faceTracks).toEqual([]);
    useAnimationStore.getState().redo();
    expect(useAnimationStore.getState().active()?.faceTracks?.[0].keys).toHaveLength(1);
    expect(useAnimationStore.getState().deleteFaceKey('0', 'eyeBlinkLeft', 1)).toBe(true);
    expect(useAnimationStore.getState().active()?.faceTracks).toEqual([]);
  });

  it('缩短时长会清理越界的表情关键帧', () => {
    useAnimationStore.getState().createAnimation('脸部');
    useAnimationStore.getState().upsertFaceKey('0', 'smile', 3, 0.7);
    useAnimationStore.getState().setDuration(2);
    expect(useAnimationStore.getState().active()?.faceTracks).toEqual([]);
  });

  it('切换动画会加载各自镜头路径，撤销新动画也恢复原动画与镜头', () => {
    const firstId = useAnimationStore.getState().createAnimation('镜头 A');
    const firstPlan = createScenePlan({ animationId: firstId, prompt: '挥手', duration: 4, source: 'rules', props: [], actions: [],
      cameraKeyframes: [{ time: 0, position: [1, 2, 3], target: [0, 1, 0], fov: 40 }], cameraEnabled: true, cameraAutoGenerated: true });
    usePrevisStore.getState().setActionPrevis(firstId, { prompt: firstPlan.prompt, segments: [], scenePlan: firstPlan });
    useCameraStore.getState().activateAnimation(firstId, firstPlan.camera, 4);

    const secondId = useAnimationStore.getState().createAnimation('镜头 B');
    expect(useCameraStore.getState().keyframes).toEqual([]);
    const secondPlan = createScenePlan({ animationId: secondId, prompt: '鞠躬', duration: 4, source: 'rules', props: [], actions: [],
      cameraKeyframes: [{ time: 0, position: [4, 3, 2], target: [0, 1, 0], fov: 55 }], cameraEnabled: true });
    usePrevisStore.getState().setActionPrevis(secondId, { prompt: secondPlan.prompt, segments: [], scenePlan: secondPlan });

    useAnimationStore.getState().selectAnimation(firstId);
    expect(useCameraStore.getState().keyframes).toEqual(firstPlan.camera.keyframes);
    expect(useCameraStore.getState().autoGenerated).toBe(true);
    useAnimationStore.getState().selectAnimation(secondId);
    expect(useCameraStore.getState().keyframes).toEqual(secondPlan.camera.keyframes);

    useAnimationStore.getState().undo();
    expect(useAnimationStore.getState().activeId).toBe(firstId);
    expect(useCameraStore.getState().activeAnimationId).toBe(firstId);
    expect(useCameraStore.getState().keyframes).toEqual(firstPlan.camera.keyframes);
    useAnimationStore.getState().redo();
    expect(useAnimationStore.getState().activeId).toBe(secondId);
    expect(useCameraStore.getState().keyframes).toEqual(secondPlan.camera.keyframes);
  });
});
