import { beforeEach, describe, expect, it } from 'vitest';
import { createScenePlan } from '../src/core/previs/scenePlan';
import { usePrevisStore } from '../src/stores/previsStore';
import { useEffectsStore } from '../src/stores/effectsStore';
import type { StageProp } from '../src/core/previs/world';

describe('previs store scene plan sync', () => {
  beforeEach(() => { usePrevisStore.getState().clear(); useEffectsStore.getState().clear(); });

  it('keeps saved scene plan aligned with edited props, camera, effects, and animation duration', () => {
    const plan = createScenePlan({ animationId: 'a', prompt: '走到桌前', duration: 4, source: 'rules', props: [], actions: [] });
    usePrevisStore.getState().setActionPrevis('a', { prompt: plan.prompt, segments: [], scenePlan: plan });
    const table: StageProp = { id: 't', kind: 'table', position: [2, 0, 0], rotationY: 0, size: { width: 1, height: 0.8, length: 0.7 } };
    const keyframe = { time: 2, position: [3, 2, 4] as [number, number, number], target: [0, 1, 0] as [number, number, number], fov: 40 };
    const effect = { id: 'fx', animationId: 'a', kind: 'dust' as const, time: 2, duration: 0.5, position: [0, 0, 0] as [number, number, number], scale: 1, color: '#aaaaaa' };
    usePrevisStore.getState().syncEditorContext([table], [effect], [keyframe], { a: 6 });
    const next = usePrevisStore.getState().byAnimationId.a.scenePlan!;
    expect(next.environment.props).toEqual([table]);
    expect(next.effects).toEqual([effect]);
    expect(next.camera.keyframes).toEqual([keyframe]);
    expect(next.duration).toBe(6);
  });

  it('syncs the active animation camera without overwriting another shot path', () => {
    const keyA = { time: 0, position: [1, 2, 3] as [number, number, number], target: [0, 1, 0] as [number, number, number], fov: 40 };
    const keyB = { time: 0, position: [7, 4, 2] as [number, number, number], target: [0, 1, 0] as [number, number, number], fov: 55 };
    const planA = createScenePlan({ animationId: 'camera-a', prompt: '挥手', duration: 4, source: 'rules', props: [], actions: [], cameraKeyframes: [keyA], cameraEnabled: true, cameraAutoGenerated: true });
    const planB = createScenePlan({ animationId: 'camera-b', prompt: '鞠躬', duration: 4, source: 'rules', props: [], actions: [], cameraKeyframes: [keyB], cameraEnabled: true });
    usePrevisStore.getState().setActionPrevis('camera-a', { prompt: planA.prompt, segments: [], scenePlan: planA });
    usePrevisStore.getState().setActionPrevis('camera-b', { prompt: planB.prompt, segments: [], scenePlan: planB });

    const edited = { ...keyA, position: [2, 3, 4] as [number, number, number] };
    usePrevisStore.getState().syncEditorContext([], [], [edited], { 'camera-a': 4, 'camera-b': 4 }, 'camera-a', true, false);

    expect(usePrevisStore.getState().byAnimationId['camera-a'].scenePlan?.camera).toMatchObject({ keyframes: [edited], enabled: true, autoGenerated: false });
    expect(usePrevisStore.getState().byAnimationId['camera-b'].scenePlan?.camera).toMatchObject({ keyframes: [keyB], enabled: true });
  });

  it('clears removed prop references from action targets, contacts, and global target state', () => {
    const opponent: StageProp = { id: 'opponent-a', kind: 'opponent', position: [0, 0, 1.6], rotationY: Math.PI, size: { width: 0.62, height: 1.72, length: 0.42 } };
    const actions = [{ t0: 0, t1: 1, template: 'punch', clause: '攻击对手', targetPropId: opponent.id }];
    const contacts = [
      { actionIndex: 0, phase: 'punch', bodyPart: 'hand' as const, propId: opponent.id, surface: 'interaction-point' as const, relation: 'rest' as const },
      { actionIndex: 1, phase: 'lie', bodyPart: 'back' as const, propId: 'ground', surface: 'ground' as const, relation: 'support' as const },
    ];
    const plan = createScenePlan({ animationId: 'remove-target', prompt: '攻击对手', duration: 1, source: 'rules', props: [opponent], actions, contacts, target: { propId: opponent.id, distanceMeters: 0.5 } });
    usePrevisStore.getState().setActionPrevis('remove-target', { prompt: plan.prompt, segments: actions, contacts, scenePlan: plan });

    usePrevisStore.getState().syncEditorContext([], [], [], { 'remove-target': 1 });

    const next = usePrevisStore.getState().byAnimationId['remove-target'];
    expect(next.segments[0]).not.toHaveProperty('targetPropId');
    expect(next.scenePlan?.actions[0]).not.toHaveProperty('targetPropId');
    expect(next.contacts).toEqual([contacts[1]]);
    expect(next.scenePlan?.target).toEqual({});
    expect(next.scenePlan?.environment.props).toEqual([]);
    expect(next.warnings?.join()).toMatch(/已清除动作、全局目标和接触中的失效引用.*未自动重生成/);
  });

  it('toggles field locks without changing the plan contents', () => {
    const plan = createScenePlan({ animationId: 'locked', prompt: '走到桌前', duration: 4, source: 'rules', props: [], actions: [] });
    usePrevisStore.getState().setActionPrevis('locked', { prompt: plan.prompt, segments: [], scenePlan: plan });
    usePrevisStore.getState().togglePlanLock('locked', 'camera');
    expect(usePrevisStore.getState().byAnimationId.locked.scenePlan?.lockedFields).toContain('camera');
    usePrevisStore.getState().togglePlanLock('locked', 'camera');
    expect(usePrevisStore.getState().byAnimationId.locked.scenePlan?.lockedFields).not.toContain('camera');
  });

  it('retimes linked effects with their action and saves the same time into the plan', () => {
    const actions = [
      { t0: 0, t1: 2, template: 'sword', clause: '挥剑' },
      { t0: 2, t1: 4, template: 'block', clause: '格挡' },
    ];
    const plan = createScenePlan({ animationId: 'retime', prompt: '先挥剑再格挡', duration: 4, source: 'rules', props: [], actions,
      effects: [{ id: 'fx-retime', animationId: 'retime', actionIndex: 1, kind: 'impact', time: 3, duration: 0.2, position: [0, 1, 0], scale: 1, color: '#ffffff' }] });
    usePrevisStore.getState().setActionPrevis('retime', { prompt: plan.prompt, segments: actions, scenePlan: plan });
    useEffectsStore.getState().replace(plan.effects);
    usePrevisStore.getState().updateSegments('retime', [actions[0], { ...actions[1], t0: 1, t1: 7 }]);
    expect(useEffectsStore.getState().events[0].time).toBe(4);
    expect(usePrevisStore.getState().byAnimationId.retime.scenePlan?.effects[0].time).toBe(4);
  });

  it('rebinds contacts when action stages are reordered and drops contacts for replaced action types', () => {
    const actions = [
      { t0: 0, t1: 1, template: 'march', clause: '走到手机前', targetPropId: 'phone' },
      { t0: 1, t1: 2, template: 'reach', clause: '拿起手机', targetPropId: 'phone' },
      { t0: 2, t1: 3, template: 'lie', clause: '躺下' },
    ];
    const plan = createScenePlan({ animationId: 'contact-rebind', prompt: '走到手机前拿起手机再躺下', duration: 3, source: 'rules', props: [], actions,
      contacts: [
        { actionIndex: 1, phase: 'reach', bodyPart: 'hand', propId: 'phone', surface: 'interaction-point', relation: 'approach' },
        { actionIndex: 2, phase: 'lie', bodyPart: 'back', propId: 'ground', surface: 'ground', relation: 'support' },
      ] });
    plan.events = [
      { time: 1, actionIndex: 1, label: '拿起手机' },
      { time: 2.5, actionIndex: 2, label: '躺卧中' },
    ];
    plan.effects = [
      { id: 'fx-reach', animationId: 'contact-rebind', actionIndex: 1, kind: 'impact', time: 1.5, duration: 0.2, position: [0, 1, 0], scale: 1, color: '#ffffff' },
      { id: 'fx-lie', animationId: 'contact-rebind', actionIndex: 2, kind: 'dust', time: 2.5, duration: 0.2, position: [0, 0, 0], scale: 1, color: '#ffffff' },
    ];
    usePrevisStore.getState().setActionPrevis('contact-rebind', { prompt: plan.prompt, segments: actions, contacts: plan.contacts, scenePlan: plan });
    useEffectsStore.getState().replace(plan.effects);

    const reordered = [
      { ...actions[2], t0: 0, t1: 1 },
      { ...actions[0], t0: 1, t1: 2 },
      { ...actions[1], t0: 2, t1: 3 },
    ];
    usePrevisStore.getState().updateSegments('contact-rebind', reordered);

    expect(usePrevisStore.getState().byAnimationId['contact-rebind'].scenePlan?.contacts.map((contact) => contact.actionIndex)).toEqual([2, 0]);
    expect(usePrevisStore.getState().byAnimationId['contact-rebind'].scenePlan?.events).toEqual([
      { time: 2, actionIndex: 2, label: '拿起手机' },
      { time: 0.5, actionIndex: 0, label: '躺卧中' },
    ]);
    expect(useEffectsStore.getState().events.map((event) => [event.id, event.actionIndex, event.time])).toEqual([
      ['fx-reach', 2, 2.5], ['fx-lie', 0, 0.5],
    ]);

    const retargeted = [...reordered];
    retargeted[2] = { ...retargeted[2], targetPropId: 'table' };
    usePrevisStore.getState().updateSegments('contact-rebind', retargeted);
    expect(usePrevisStore.getState().byAnimationId['contact-rebind'].scenePlan?.contacts.find((contact) => contact.actionIndex === 2)?.propId).toBe('table');

    const replaced = [{ ...reordered[0], template: 'stand', clause: '站立' }, reordered[1], reordered[2]];
    usePrevisStore.getState().updateSegments('contact-rebind', replaced);
    expect(usePrevisStore.getState().byAnimationId['contact-rebind'].contacts?.map((contact) => contact.actionIndex)).toEqual([2]);
    expect(usePrevisStore.getState().byAnimationId['contact-rebind'].scenePlan?.events).toEqual([
      { time: 2, actionIndex: 2, label: '拿起手机' },
    ]);
    expect(useEffectsStore.getState().events).toEqual([]);
  });

  it('locked storyboard prompts reject AI updates, then accept them after unlock', () => {
    const plan = createScenePlan({ animationId: 'story', prompt: '挥手', duration: 4, source: 'rules', props: [], actions: [] });
    plan.storyboard = { shots: [{ index: 1, visualStyle: '原始风格', continuity: '原始连续性' }] };
    usePrevisStore.getState().setActionPrevis('story', { prompt: plan.prompt, segments: [], scenePlan: plan });
    usePrevisStore.getState().togglePlanLock('story', 'storyboard');
    usePrevisStore.getState().updateStoryboardPrompts('story', [{ index: 1, visualStyle: '不应覆盖', continuity: '不应覆盖' }]);
    expect(usePrevisStore.getState().byAnimationId.story.scenePlan?.storyboard?.shots[0].visualStyle).toBe('原始风格');

    usePrevisStore.getState().togglePlanLock('story', 'storyboard');
    usePrevisStore.getState().updateStoryboardPrompts('story', [{ index: 1, visualStyle: '新风格', continuity: '新连续性' }]);
    expect(usePrevisStore.getState().byAnimationId.story.scenePlan?.storyboard?.shots[0].visualStyle).toBe('新风格');
  });
});
