import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { createEmptyProject } from '../src/core/project/schema';
import { checkCharacterBind, parseProjectFile, serializeProject } from '../src/core/project/serialize';
import { createEmptyAnimation } from '../src/core/animation/types';
import type { CharacterMeta } from '../src/types/global';
import { createScenePlan } from '../src/core/previs/scenePlan';
import { buildSkeletonTree } from '../src/core/skeleton/buildSkeletonTree';
import { rebuildSketchCharacter } from '../src/services/sketch/buildSketchCharacter';
import { buildDemoCharacter } from '../src/services/demo/buildDemoCharacter';
import { DEFAULT_APPEARANCE, RANGES } from '../src/core/character/appearance';
import { LANDMARK_ORDER, restoreSketchDraft } from '../src/core/rig/sketchToSpec';

const Q: [number, number, number, number] = [0, 0, 0, 1];

describe('project save/load', () => {
  it('browser mismatch fixture parses and keeps its project animation', () => {
    const fixture = readFileSync(new URL('./fixtures/project-character-mismatch.json', import.meta.url), 'utf8');
    const { project } = parseProjectFile(fixture);

    expect(project.character?.fileName).toBe('original-person.glb');
    expect(project.animations.map((animation) => animation.name)).toEqual(['项目动画保留验证']);
    expect(project.activeAnimationId).toBe('fixture-mismatch-animation');
  });

  it('序列化往返保持动画', () => {
    const p = createEmptyProject();
    const a = createEmptyAnimation('挥剑', 30, 3);
    a.tracks.push({ boneName: 'Hips', position: [], rotation: [{ time: 1, value: Q, interp: 'linear' }], scale: [] });
    a.faceTracks = [{ meshPath: '0/2', targetName: 'eyeBlinkLeft', keys: [{ time: 1.2, value: 0.9, interp: 'linear' }] }];
    p.animations.push(a);
    p.camera.enabled = true;
    p.camera.autoGenerated = true;
    p.camera.keyframes = [{ time: 0, position: [2, 1, 3], target: [0, 1, 0], fov: 45 }];
    p.scene.props = [{ id: 'sword-main', kind: 'sword', position: [0, 1, 0], rotationY: 0, size: { width: 0.04, height: 0.04, length: 0.9 }, attachTo: 'hand.R', attachOffset: [0.01, 0.02, 0] }];
    p.scene.effects = [{ id: 'fx-1', kind: 'slash', time: 1.2, duration: 0.3, position: [0, 1.3, 0], scale: 0.8, color: '#7dd3fc' }];
    p.previs = { [a.id]: { prompt: '慢慢挥剑', segments: [{ t0: 0, t1: 3, template: 'sword', clause: '慢动作挥剑', intensity: 0.7, speed: 0.6, targetPropId: 'sword-main' }] } };
    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.animations.length).toBe(1);
    expect(project.animations[0].name).toBe('挥剑');
    expect(project.animations[0].tracks[0].rotation[0].time).toBe(1);
    expect(project.animations[0].faceTracks?.[0]).toMatchObject({ meshPath: '0/2', targetName: 'eyeBlinkLeft', keys: [{ time: 1.2, value: 0.9 }] });
    expect(project.camera.enabled).toBe(true);
    expect(project.camera.autoGenerated).toBe(true);
    expect(project.camera.keyframes).toHaveLength(1);
    expect(project.scene.props?.[0].attachTo).toBe('hand.R');
    expect(project.scene.effects?.[0].time).toBe(1.2);
    expect(project.previs?.[a.id].segments[0]).toMatchObject({ intensity: 0.7, speed: 0.6 });
    expect(project.previs?.[a.id].segments[0].targetPropId).toBe('sword-main');
    const leftHand = structuredClone(p);
    leftHand.scene.props![0].attachTo = 'hand.L';
    expect(parseProjectFile(serializeProject(leftHand)).project.scene.props?.[0].attachTo).toBe('hand.L');
    const detached = structuredClone(p);
    detached.scene.props![0].attachTo = null;
    expect(parseProjectFile(serializeProject(detached)).project.scene.props?.[0].attachTo).toBeNull();
  });

  it('保存每个动画自己的镜头并恢复当前选中的动画', () => {
    const project = createEmptyProject();
    const first = createEmptyAnimation('第一镜', 30, 4);
    const second = createEmptyAnimation('第二镜', 30, 6);
    project.animations = [first, second];
    project.activeAnimationId = second.id;
    const camera = { time: 2, position: [4, 3, 2] as [number, number, number], target: [0, 1, 0] as [number, number, number], fov: 52 };
    const plan = createScenePlan({ animationId: second.id, prompt: '转身', duration: 6, source: 'rules', props: [], actions: [],
      cameraKeyframes: [camera], cameraEnabled: true, cameraAutoGenerated: true });
    project.previs = { [second.id]: { prompt: plan.prompt, segments: [], scenePlan: plan } };

    const roundTrip = parseProjectFile(serializeProject(project)).project;

    expect(roundTrip.activeAnimationId).toBe(second.id);
    expect(roundTrip.previs?.[second.id].scenePlan?.camera).toMatchObject({ keyframes: [camera], enabled: true, autoGenerated: true });
  });

  it('非法 JSON 与越界 key 分别抛错/警告', () => {
    expect(() => parseProjectFile('not json')).toThrow();
    const p = createEmptyProject();
    const a = createEmptyAnimation('X', 30, 2);
    a.tracks.push({ boneName: 'H', position: [{ time: 9, value: [0, 0, 0], interp: 'linear' }], rotation: [], scale: [] });
    p.animations.push(a);
    const { warnings } = parseProjectFile(serializeProject(p));
    expect(warnings.length).toBeGreaterThan(0);
  });

  it('旧版动画文件自动补齐空表情轨道', () => {
    const p = createEmptyProject();
    const animation = createEmptyAnimation('旧动画');
    delete animation.faceTracks;
    p.animations.push(animation);
    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.animations[0].faceTracks).toEqual([]);
  });

  it('手绘角色的点位与生成参数随项目保存，支持打开时重建', () => {
    const p = createEmptyProject();
    p.character = {
      id: 'sketch-1', fileName: 'sketch-character.glb', fileSize: 0,
      gltfInfo: { meshes: 27, materials: 3, bones: 17, hasSkin: true, hasAnimations: 0 },
      sketchSource: {
        landmarks: {
          head: { x: 200, y: 40 }, neck: { x: 200, y: 110 }, shoulder: { x: 150, y: 130 },
          elbow: { x: 140, y: 220 }, wrist: { x: 145, y: 300 }, hips: { x: 200, y: 280 },
          knee: { x: 195, y: 390 }, ankle: { x: 195, y: 500 },
        },
        options: { headR: 0.115, thickness: 1 },
      },
    };
    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.character?.sketchSource).toEqual(p.character.sketchSource);
    const rebuilt = rebuildSketchCharacter(project.character!);
    try {
      expect(rebuilt.meta.id).toBe('sketch-1');
      expect(buildSkeletonTree(rebuilt.scene).boneCount).toBe(17);
      expect(restoreSketchDraft(rebuilt.meta.sketchSource!).points).toEqual(LANDMARK_ORDER.map((key) => p.character!.sketchSource!.landmarks[key]));
      expect(restoreSketchDraft(rebuilt.meta.sketchSource!).options).toEqual(p.character.sketchSource.options);
    } finally {
      rebuilt.dispose();
    }
  });

  it('程序化角色的外观配方随项目保存，支持打开时重建', () => {
    const p = createEmptyProject();
    p.character = {
      id: 'demo-male', fileName: 'previs-male.glb', fileSize: 0,
      gltfInfo: { meshes: 30, materials: 8, bones: 17, hasSkin: true, hasAnimations: 0 },
      appearanceSource: {
        gender: 'female', height: 1.72, build: 0.6, faceShape: 'heart',
        eyeSize: 1.15, browThickness: 0.9, noseSize: 0.95, mouthWidth: 1.05,
        hairStyle: 'long', hairColor: '#112233', skinColor: '#d4aa8c',
        clothColor: '#8f7f9e', skinRoughness: 0.5,
      },
    };
    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.character?.appearanceSource).toEqual(p.character.appearanceSource);
    // 按配方重建出的几何与原配方一致
    const demo = buildDemoCharacter('female', project.character!.appearanceSource!);
    try {
      expect(demo.meta.appearanceSource).toEqual(p.character.appearanceSource);
      expect(demo.scene.userData['themable']).toBe(true);
    } finally {
      demo.dispose();
    }
  });

  it('外观配方里的非法值在解析时被规范化而非报错', () => {
    const p = createEmptyProject();
    p.character = {
      id: 'demo-bad', fileName: 'previs-male.glb', fileSize: 0,
      gltfInfo: { meshes: 30, materials: 8, bones: 17, hasSkin: true, hasAnimations: 0 },
      appearanceSource: { height: 99, faceShape: 'nope' as never, skinColor: 'bogus' } as never,
    };
    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.character?.appearanceSource?.height).toBe(RANGES.height.max);
    expect(project.character?.appearanceSource?.faceShape).toBe(DEFAULT_APPEARANCE.faceShape);
    expect(project.character?.appearanceSource?.skinColor).toBe(DEFAULT_APPEARANCE.skinColor);
  });

  it('在项目解析阶段拒绝缺失骨架元数据或无效手绘重建配方', () => {
    const project = createEmptyProject();
    project.character = {
      id: 'sketch-valid', fileName: 'sketch-character.glb', fileSize: 0,
      gltfInfo: { meshes: 27, materials: 3, bones: 17, hasSkin: true, hasAnimations: 0 },
      sketchSource: {
        landmarks: {
          head: { x: 200, y: 40 }, neck: { x: 200, y: 110 }, shoulder: { x: 150, y: 130 },
          elbow: { x: 140, y: 220 }, wrist: { x: 145, y: 300 }, hips: { x: 200, y: 280 },
          knee: { x: 195, y: 390 }, ankle: { x: 195, y: 500 },
        },
        options: { headR: 0.115, thickness: 1 },
      },
    };
    const missingBoneCount = JSON.parse(serializeProject(project));
    delete missingBoneCount.character.gltfInfo.bones;
    expect(() => parseProjectFile(JSON.stringify(missingBoneCount))).toThrow(/character 缺少有效的 id、文件信息或 gltfInfo/);

    const missingLandmark = JSON.parse(serializeProject(project));
    delete missingLandmark.character.sketchSource.landmarks.wrist;
    expect(() => parseProjectFile(JSON.stringify(missingLandmark))).toThrow(/landmarks\.wrist 无效/);

    const impossiblePose = JSON.parse(serializeProject(project));
    impossiblePose.character.sketchSource.landmarks.ankle.y = 100;
    expect(() => parseProjectFile(JSON.stringify(impossiblePose))).toThrow(/上下顺序不合理/);
  });

  it('未生成角色的手绘草稿也随项目保存并过滤损坏点位', () => {
    const p = createEmptyProject();
    p.sketchDraft = {
      points: [
        { x: 200, y: 40 }, { x: 200, y: 110 }, { x: 150, y: 130 }, { x: 140, y: 220 },
        { x: 145, y: 300 }, null, { x: Number.NaN, y: 390 }, null,
      ],
      options: { headR: 0.2, thickness: 0.5 },
    };

    const { project, warnings } = parseProjectFile(serializeProject(p));

    expect(warnings).toEqual([]);
    expect(project.character).toBeNull();
    expect(project.sketchDraft).toEqual({
      points: [
        { x: 200, y: 40 }, { x: 200, y: 110 }, { x: 150, y: 130 }, { x: 140, y: 220 },
        { x: 145, y: 300 }, null, null, null,
      ],
      options: { headR: 0.15, thickness: 0.7 },
    });
  });

  it('完整预演方案保存后保留 AI 编辑所需的锁、来源、接触和分镜信息', () => {
    const p = createEmptyProject();
    const animation = createEmptyAnimation('床边预演', 30, 8);
    p.animations.push(animation);
    const bed = {
      id: 'bed-main', kind: 'bed' as const, position: [1, 0, 0] as [number, number, number], rotationY: 0,
      size: { width: 1.4, height: 0.6, length: 2 },
    };
    const plan = createScenePlan({
      animationId: animation.id,
      prompt: '人物走到床边躺下睡觉',
      duration: 8,
      source: 'model',
      model: 'local-llm',
      props: [bed],
      actions: [
        { t0: 0, t1: 3, template: 'march', clause: '走到床边', targetPropId: bed.id, intensity: 0.8, speed: 0.9 },
        { t0: 3, t1: 8, template: 'lie', clause: '躺下并入睡', targetPropId: bed.id },
      ],
      contacts: [{ phase: 'lie', bodyPart: 'back', propId: bed.id, surface: 'mattress', relation: 'support' }],
      target: { propId: bed.id, distanceMeters: 0.45 },
      lockedFields: ['environment', 'contacts'],
      warnings: ['床体支撑尚未进行物理碰撞验证'],
    });
    plan.interpretation.fieldEvidence!.actions = {
      source: 'model', certainty: 'medium', reason: '语言模型生成的动作阶段',
    };
    plan.storyboard = { shots: [{ index: 1, visualStyle: '自然暖光', continuity: '保持同一套睡衣' }] };
    plan.camera.keyframes = [{ time: 4, position: [2, 1.6, 3], target: [1, 0.6, 0], fov: 48 }];
    plan.effects = [{ id: 'fx-dust', kind: 'dust', time: 3, duration: 0.7, position: [1, 0.1, 0], scale: 0.6, color: '#c4b5a5' }];
    p.previs = { [animation.id]: {
      prompt: plan.prompt,
      segments: structuredClone(plan.actions),
      contacts: structuredClone(plan.contacts),
      warnings: [...plan.interpretation.reasons],
      scenePlan: plan,
    } };

    const { project, warnings } = parseProjectFile(serializeProject(p));
    expect(warnings).toEqual([]);
    expect(project.previs?.[animation.id]).toEqual(p.previs[animation.id]);
  });

  it('损坏或越界的表情关键帧只产生校验警告，不使项目载入崩溃', () => {
    const p = createEmptyProject();
    const animation = createEmptyAnimation('损坏表情轨道');
    animation.faceTracks = [{ meshPath: '0', targetName: 'smile', keys: [
      { time: Number.NaN, value: 1.4, interp: 'linear' },
    ] }];
    p.animations.push(animation);
    const { warnings } = parseProjectFile(serializeProject(p));
    expect(warnings.join()).toMatch(/face key out of range/);
    expect(warnings.join()).toMatch(/face weight out of range/);
  });
});

describe('checkCharacterBind', () => {
  const meta: CharacterMeta = {
    id: 'c1',
    fileName: 'wuxia.glb',
    fileSize: 12345,
    gltfInfo: { meshes: 3, materials: 2, bones: 40, hasSkin: true, hasAnimations: 0 },
  };
  it('一致/缺失/不一致', () => {
    const p = createEmptyProject();
    p.character = meta;
    expect(checkCharacterBind(meta, p)).toBe('match');
    expect(checkCharacterBind(null, p)).toBe('missing');
    expect(checkCharacterBind({ ...meta, fileSize: 1 }, p)).toBe('mismatch');
    expect(checkCharacterBind(meta, createEmptyProject())).toBe('missing');
  });
});
