import type { CameraKeyframe } from '../camera/track';
import { actionIndexAtTime, type PrevisEffectEvent } from './effects';
import { doorHandleWorldPosition, findStagePropOverlaps, findStagePropRoomOverflows, getPropCollisionBoxes, STAGE_PROP_SIZE_LIMITS, type ContactConstraint, type StageProp } from './world';
import { isKnownTemplate } from '../../services/motion/procedural';

export interface PlannedAction {
  t0: number;
  t1: number;
  template: string;
  clause: string;
  intensity?: number;
  speed?: number;
  targetPropId?: string;
}

export interface ScenePlan {
  version: 1;
  animationId: string;
  prompt: string;
  duration: number;
  character: { id?: string; label: string; heightMeters?: number };
  interpretation: {
    source: 'model' | 'rules';
    model?: string;
    certainty: 'high' | 'medium' | 'low';
    reasons: string[];
    questions: string[];
    missingInfo?: string[];
    fieldEvidence?: Record<string, { source: 'user' | 'model' | 'editor' | 'rules'; certainty: 'high' | 'medium' | 'low'; reason: string }>;
  };
  environment: { props: StageProp[] };
  actions: PlannedAction[];
  contacts: ContactConstraint[];
  weapons: Array<{ propId: string; kind: 'sword'; attachedTo: string | null }>;
  effects: PrevisEffectEvent[];
  camera: { keyframes: CameraKeyframe[]; enabled?: boolean; autoGenerated?: boolean };
  storyboard?: { shots: Array<{ index: number; visualStyle: string; continuity: string }> };
  events: Array<{ time: number; actionIndex: number; label: string }>;
  target: { propId?: string; distanceMeters?: number; obstructed?: boolean };
  lockedFields: string[];
}

export interface ScenePlanIssue {
  level: 'error' | 'warning';
  path: string;
  message: string;
}

function segmentIntersectsPropBounds(start: number[], end: number[], prop: StageProp, padding = 0.06): boolean {
  const cosine = Math.cos(prop.rotationY);
  const sine = Math.sin(prop.rotationY);
  const toLocal = (point: number[]) => {
    const dx = point[0] - prop.position[0];
    const dz = point[2] - prop.position[2];
    return [dx * cosine + dz * sine, point[1] - prop.position[1], -dx * sine + dz * cosine];
  };
  const a = toLocal(start);
  const b = toLocal(end);
  return getPropCollisionBoxes(prop).some((box) => {
    const minimum = box.center.map((value, axis) => value - box.size[axis] / 2 - padding);
    const maximum = box.center.map((value, axis) => value + box.size[axis] / 2 + padding);
    let enter = 0;
    let leave = 1;
    for (let axis = 0; axis < 3; axis++) {
      const delta = b[axis] - a[axis];
      if (Math.abs(delta) < 1e-8) {
        if (a[axis] < minimum[axis] || a[axis] > maximum[axis]) return false;
        continue;
      }
      let near = (minimum[axis] - a[axis]) / delta;
      let far = (maximum[axis] - a[axis]) / delta;
      if (near > far) [near, far] = [far, near];
      enter = Math.max(enter, near);
      leave = Math.min(leave, far);
      if (enter > leave) return false;
    }
    return true;
  });
}

function contactSurfaceWorldHeight(prop: StageProp, surface: ContactConstraint['surface']): number | undefined {
  if (surface === 'mattress' && prop.kind === 'bed') return prop.position[1] + prop.size.height;
  if (surface === 'seat') {
    // 椅面顶用真实座板几何 0.48h + 0.04（与 getPropCollisionBoxes / WorldStage 一致）
    if (prop.kind === 'chair') return prop.position[1] + prop.size.height * 0.48 + 0.04;
    if (prop.kind === 'sofa') return prop.position[1] + prop.size.height * 0.58;
    if (prop.kind === 'bed') return prop.position[1] + prop.size.height;
  }
  if (surface === 'handle' && prop.kind === 'door') return doorHandleWorldPosition(prop)[1];
  if (surface === 'interaction-point' && contactSurfaceNeedsSupportHeight(prop)) return prop.position[1] + prop.size.height;
  return undefined;
}

function contactSurfaceNeedsSupportHeight(prop: StageProp): boolean {
  return prop.kind === 'table' || prop.kind === 'bed' || prop.kind === 'chair' || prop.kind === 'sofa';
}

function plausibleContactHeightRange(surface: ContactConstraint['surface']): [number, number] | undefined {
  if (surface === 'mattress') return [0.15, 0.62];
  if (surface === 'seat') return [0.16, 0.4];
  if (surface === 'handle') return [0.35, 0.72];
  if (surface === 'interaction-point') return [0.28, 0.78];
  return undefined;
}

function segmentIntersectsStaticSword(start: number[], end: number[], sword: StageProp, padding: number): boolean {
  const cosine = Math.cos(sword.rotationY);
  const sine = Math.sin(sword.rotationY);
  const toLocal = (point: number[]) => {
    const dx = point[0] - sword.position[0];
    const dz = point[2] - sword.position[2];
    return [dx * cosine + dz * sine, point[1] - sword.position[1], -dx * sine + dz * cosine];
  };
  const a = toLocal(start);
  const b = toLocal(end);
  const minimum = [-sword.size.width / 2 - padding, -0.14 - padding, -sword.size.height / 2 - padding];
  const maximum = [sword.size.width / 2 + padding, sword.size.length + 0.03 + padding, sword.size.height / 2 + padding];
  let enter = 0;
  let leave = 1;
  for (let axis = 0; axis < 3; axis++) {
    const delta = b[axis] - a[axis];
    if (Math.abs(delta) < 1e-8) {
      if (a[axis] < minimum[axis] || a[axis] > maximum[axis]) return false;
      continue;
    }
    let near = (minimum[axis] - a[axis]) / delta;
    let far = (maximum[axis] - a[axis]) / delta;
    if (near > far) [near, far] = [far, near];
    enter = Math.max(enter, near);
    leave = Math.min(leave, far);
    if (enter > leave) return false;
  }
  return true;
}

/** Snapshot the current editor state into one portable, inspectable previs document. */
export function createScenePlan(input: {
  animationId: string;
  prompt: string;
  duration: number;
  character?: ScenePlan['character'];
  source: 'model' | 'rules';
  model?: string;
  props: StageProp[];
  actions: PlannedAction[];
  contacts?: ContactConstraint[];
  effects?: PrevisEffectEvent[];
  cameraKeyframes?: CameraKeyframe[];
  cameraEnabled?: boolean;
  cameraAutoGenerated?: boolean;
  target?: ScenePlan['target'];
  warnings?: string[];
  interpretation?: { certainty?: 'high' | 'medium' | 'low'; reasons?: string[]; questions?: string[]; missingInfo?: string[] };
  lockedFields?: string[];
}): ScenePlan {
  const warnings = input.warnings ?? [];
  const uncertain = warnings.length > 0 || input.actions.some((action) => action.template === 'sway');
  const represented = input.actions.some((action) => action.template !== 'sway');
  const questions = new Set<string>();
  for (const question of input.interpretation?.questions ?? []) if (question.trim()) questions.add(question.trim());
  for (const warning of warnings) {
    const ambiguous = warning.match(/场景中有多个(.+?)（([^）]+)），无法仅凭描述确定目标/);
    if (ambiguous) questions.add(`${ambiguous[1]}目标不明确，请选择具体道具：${ambiguous[2]}`);
  }
  if (warnings.some((warning) => /场景中没有床|没有床/.test(warning))) questions.add('需要躺卧支撑，但场景没有床：按地面仰卧预演，还是添加床后再生成？');
  if (warnings.some((warning) => /没有手机/.test(warning))) questions.add('描述里提到了手机，但场景里没有手机：是否添加手机并重新生成交互？');
  if (warnings.some((warning) => /没有.*门/.test(warning))) questions.add('描述里提到了门，但场景里没有门：是否先添加门并设置位置？');
  if (!represented) questions.add('这句描述没有匹配到明确动作：请指定动作，或连接 LLM 生成动作分段。');
  if (warnings.some((warning) => /路径.*相交|障碍/.test(warning))) questions.add('角色路径可能被道具挡住：是否调整道具位置或重新规划走位？');
  const certaintyRank = { high: 2, medium: 1, low: 0 } as const;
  const inferredCertainty = !represented || warnings.some((warning) => /未识别|没有|缺少|无法|尚未/.test(warning))
    ? 'low'
    : input.source === 'model' || uncertain ? 'medium' : 'high';
  const requestedCertainty = input.interpretation?.certainty ?? inferredCertainty;
  // Model confidence can lower trust, but cannot override contradictions found by local validation.
  const certainty = certaintyRank[requestedCertainty] < certaintyRank[inferredCertainty] ? requestedCertainty : inferredCertainty;
  const reasons = [...new Set([...warnings, ...(input.interpretation?.reasons ?? [])])];
  const missingInfo = [...new Set(input.interpretation?.missingInfo ?? [])];
  return {
    version: 1,
    animationId: input.animationId,
    prompt: input.prompt,
    duration: input.duration,
    character: structuredClone(input.character ?? { label: '主角' }),
    interpretation: {
      source: input.source,
      model: input.model,
      certainty,
      reasons,
      questions: [...questions],
      missingInfo,
      fieldEvidence: {
        prompt: { source: 'user', certainty: 'high', reason: '保留用户原始描述' },
        actions: { source: input.source, certainty, reason: reasons[0] ?? (input.source === 'model' ? '由配置的语言模型规划，尚需按预演效果确认' : '由本地规则拆解') },
        environment: { source: 'editor', certainty: 'high', reason: '来自当前场景编辑器；未出现的物体不会自动视为已存在' },
        contacts: { source: 'rules', certainty: input.contacts?.length ? 'medium' : 'low', reason: input.contacts?.length ? '依据动作与当前道具推导的接触目标，尚非物理碰撞结果' : '未建立明确支撑或接触关系' },
        camera: { source: 'editor', certainty: input.cameraKeyframes?.length ? 'medium' : 'low', reason: input.cameraKeyframes?.length ? '来自当前镜头关键帧' : '尚无镜头路径关键帧' },
      },
    },
    environment: { props: structuredClone(input.props) },
    actions: structuredClone(input.actions),
    contacts: structuredClone(input.contacts ?? []),
    weapons: input.props.filter((prop) => prop.kind === 'sword').map((prop) => ({ propId: prop.id, kind: 'sword', attachedTo: prop.attachTo ?? null })),
    effects: structuredClone(input.effects ?? []).map((effect) => {
      if (effect.actionIndex !== undefined) return effect;
      const actionIndex = actionIndexAtTime(input.actions, effect.time);
      return actionIndex === undefined ? effect : { ...effect, actionIndex };
    }),
    camera: {
      keyframes: structuredClone(input.cameraKeyframes ?? []),
      enabled: input.cameraEnabled ?? Boolean(input.cameraKeyframes?.length),
      autoGenerated: input.cameraAutoGenerated ?? false,
    },
    events: input.actions.map((action, actionIndex) => ({ time: action.t0, actionIndex, label: action.clause })),
    target: structuredClone(input.target ?? {}),
    lockedFields: [...new Set(input.lockedFields ?? [])],
  };
}

/** Check cross references and temporal constraints before a plan is applied or exported. */
export function validateScenePlan(plan: ScenePlan): ScenePlanIssue[] {
  const issues: ScenePlanIssue[] = [];
  const propIds = new Set(plan.environment.props.map((prop) => prop.id));
  const propsById = new Map(plan.environment.props.map((prop) => [prop.id, prop]));
  const characterHeight = plan.character.heightMeters;
  const hasCharacterHeight = characterHeight !== undefined && Number.isFinite(characterHeight) && characterHeight > 0;
  if (characterHeight !== undefined && (!Number.isFinite(characterHeight) || characterHeight < 0.5 || characterHeight > 3.2)) {
    issues.push({ level: 'error', path: 'character.heightMeters', message: '人物身高必须是 0.5–3.2 米之间的有限数值' });
  }
  if (propIds.size !== plan.environment.props.length) issues.push({ level: 'error', path: 'environment.props', message: '场景中存在重复的道具 ID，接触关系无法唯一定位' });
  for (const [index, prop] of plan.environment.props.entries()) {
    const dimensions = [prop.size.width, prop.size.height, prop.size.length];
    const dimensionNames = ['width', 'height', 'length'] as const;
    const propLimits = STAGE_PROP_SIZE_LIMITS[prop.kind];
    const sizeOutsideKindBounds = !propLimits || dimensions.some((value, dimensionIndex) => {
      const [min, max] = propLimits[dimensionNames[dimensionIndex]];
      return value < min || value > max;
    });
    if (!prop.id.trim() || ![...prop.position, prop.rotationY, ...dimensions].every(Number.isFinite)
      || dimensions.some((value) => value <= 0) || sizeOutsideKindBounds) {
      issues.push({ level: 'error', path: `environment.props.${index}`, message: `场景道具 ${prop.id || index + 1} 的坐标、朝向或尺寸无效` });
    }
  }
  for (const overlap of findStagePropOverlaps(plan.environment.props)) {
    issues.push({
      level: 'warning',
      path: `environment.props.${overlap.firstPropId}`,
      message: `场景道具 ${overlap.firstPropId} 与 ${overlap.secondPropId} 的实体占位相交约 ${(overlap.overlapMeters * 100).toFixed(0)} 厘米；请调整位置、朝向或尺寸`,
    });
  }
  if (!plan.prompt.trim()) issues.push({ level: 'error', path: 'prompt', message: '预演缺少原始描述' });
  if (!Number.isFinite(plan.duration) || plan.duration <= 0) issues.push({ level: 'error', path: 'duration', message: '预演时长必须大于 0' });
  let previousEnd = 0;
  for (const [index, action] of plan.actions.entries()) {
    if (!action.clause.trim()) issues.push({ level: 'error', path: `actions.${index}.clause`, message: `动作 ${index + 1} 缺少描述` });
    if (!isKnownTemplate(action.template)) issues.push({ level: 'error', path: `actions.${index}.template`, message: `动作 ${index + 1} 使用未知动作模板 ${action.template}` });
    if (!Number.isFinite(action.t0) || !Number.isFinite(action.t1) || action.t0 < 0 || action.t1 > plan.duration || action.t1 <= action.t0) {
      issues.push({ level: 'error', path: `actions.${index}.time`, message: `动作 ${index + 1} 的时间范围无效` });
    }
    if (action.t0 < previousEnd - 1e-4) issues.push({ level: 'error', path: `actions.${index}.time`, message: `动作 ${index + 1} 与上一动作时间重叠` });
    if (action.template === 'sway') issues.push({ level: 'warning', path: `actions.${index}.template`, message: `动作 ${index + 1} 使用站立占位，未识别为具体动作` });
    if (action.intensity !== undefined && (!Number.isFinite(action.intensity) || action.intensity < 0.4 || action.intensity > 1.6)) {
      issues.push({ level: 'error', path: `actions.${index}.intensity`, message: `动作 ${index + 1} 的幅度必须在 0.4–1.6 之间` });
    }
    if (action.speed !== undefined && (!Number.isFinite(action.speed) || action.speed < 0.5 || action.speed > 2)) {
      issues.push({ level: 'error', path: `actions.${index}.speed`, message: `动作 ${index + 1} 的速度必须在 0.5–2 之间` });
    }
    if (action.targetPropId && !propIds.has(action.targetPropId)) issues.push({ level: 'error', path: `actions.${index}.targetPropId`, message: `动作 ${index + 1} 引用了场景中不存在的道具 ${action.targetPropId}` });
    if (index > 0 && Math.abs(action.t0 - previousEnd) > 1e-3) issues.push({ level: 'warning', path: `actions.${index}.time`, message: `动作 ${index + 1} 与前段之间存在 ${Math.max(0, action.t0 - previousEnd).toFixed(2)} 秒的时间空档` });
    previousEnd = action.t1;
  }
  if (plan.actions.length > 0) {
    if (plan.actions[0].t0 > 1e-3) issues.push({ level: 'warning', path: 'actions.0.time', message: '动作没有从 0 秒开始' });
    if (plan.actions.at(-1)!.t1 < plan.duration - 1e-3) issues.push({ level: 'warning', path: 'actions.end', message: '最后一个动作没有覆盖完整预演时长' });
  }
  const checkedContactHeights = new Set<string>();
  const roomFloorY = plan.environment.props.find((prop) => prop.kind === 'room')?.position[1] ?? 0;
  if (hasCharacterHeight) {
    const likelyRanges: Partial<Record<StageProp['kind'], { label: string; height: (prop: StageProp) => number; range: [number, number]; surface?: ContactConstraint['surface'] }>> = {
      bed: { label: '床面', height: (prop) => prop.position[1] + prop.size.height, range: [0.15, 0.62], surface: 'mattress' },
      chair: { label: '椅面', height: (prop) => prop.position[1] + prop.size.height * 0.48 + 0.04, range: [0.2, 0.4], surface: 'seat' },
      sofa: { label: '沙发座面', height: (prop) => prop.position[1] + prop.size.height * 0.58, range: [0.2, 0.4], surface: 'seat' },
      table: { label: '桌面', height: (prop) => prop.position[1] + prop.size.height, range: [0.28, 0.78], surface: 'interaction-point' },
      door: { label: '门高', height: (prop) => prop.position[1] + prop.size.height, range: [0.85, 1.8] },
      opponent: { label: '对手身高', height: (prop) => prop.position[1] + prop.size.height, range: [0.65, 1.35] },
    };
    for (const prop of plan.environment.props) {
      if (prop.kind === 'room' && prop.size.height / characterHeight < 1.05) {
        issues.push({ level: 'warning', path: `environment.props.${prop.id}.size.height`, message: `房间净高 ${prop.size.height.toFixed(2)} 米不足人物身高的 1.05 倍；站立或抬手动作可能碰到天花板` });
      }
      const rule = likelyRanges[prop.kind];
      if (!rule || rule.surface && plan.contacts.some((contact) => contact.propId === prop.id
        && contact.surface === rule.surface && contact.relation !== 'approach')) continue;
      const surfaceHeight = rule.height(prop);
      const relativeHeight = (surfaceHeight - roomFloorY) / characterHeight;
      if (relativeHeight < rule.range[0] || relativeHeight > rule.range[1]) {
        issues.push({ level: 'warning', path: `environment.props.${prop.id}.size.height`, message: `${rule.label}约 ${(surfaceHeight - roomFloorY).toFixed(2)} 米，占人物身高 ${(relativeHeight * 100).toFixed(0)}%；超出常见比例，请核对道具高度或人物身高` });
      }
    }
  }
  for (const [index, contact] of plan.contacts.entries()) {
    const isGround = contact.surface === 'ground' && contact.propId === 'ground';
    const prop = isGround ? undefined : propsById.get(contact.propId);
    if (contact.surface === 'ground' && !isGround) {
      issues.push({ level: 'error', path: `contacts.${index}.propId`, message: '地面支撑必须使用虚拟目标 ID ground' });
    }
    if (!isGround && !prop) issues.push({ level: 'error', path: `contacts.${index}.propId`, message: `支撑/接触目标 ${contact.propId} 不在当前场景中` });
    else if (prop && ((contact.surface === 'mattress' && prop.kind !== 'bed') || (contact.surface === 'seat' && prop.kind !== 'chair' && prop.kind !== 'sofa' && prop.kind !== 'bed') || (contact.surface === 'handle' && prop.kind !== 'door') || contact.surface === 'ground')) {
      issues.push({ level: 'error', path: `contacts.${index}.surface`, message: `${contact.surface} 接触面与${prop.kind}道具类型不匹配` });
    }
    if (prop && hasCharacterHeight && contact.relation !== 'approach') {
      const range = plausibleContactHeightRange(contact.surface);
      const surfaceHeight = contactSurfaceWorldHeight(prop, contact.surface);
      const heightKey = `${prop.id}:${contact.surface}`;
      if (range && surfaceHeight !== undefined && !checkedContactHeights.has(heightKey)) {
        checkedContactHeights.add(heightKey);
        const relativeHeight = (surfaceHeight - roomFloorY) / characterHeight;
        if (relativeHeight < range[0] || relativeHeight > range[1]) {
          issues.push({
            level: 'warning',
            path: `environment.props.${prop.id}.size.height`,
            message: `${prop.id} 的${({ mattress: '床面', seat: '座面', handle: '门把手', 'interaction-point': '支撑面', ground: '地面' } as const)[contact.surface]}高度约 ${(surfaceHeight - roomFloorY).toFixed(2)} 米，占人物身高 ${(relativeHeight * 100).toFixed(0)}%；超出常见可达/坐卧范围，请核对尺寸、离地高度或人物身高`,
          });
        }
      }
    }
    const supportedParts: Record<ContactConstraint['surface'], ContactConstraint['bodyPart'][]> = {
      mattress: ['pelvis', 'back', 'head', 'legs', 'hand'],
      seat: ['pelvis', 'hand'],
      handle: ['hand'],
      'interaction-point': ['hand'],
      ground: ['pelvis', 'back', 'head', 'legs', 'hand'],
    };
    const compatibleParts = supportedParts[contact.surface];
    if (compatibleParts && !compatibleParts.includes(contact.bodyPart)) {
      const partLabel = ({ pelvis: '髋部', back: '背部', head: '头部', legs: '腿部', hand: '手部' } as Record<string, string>)[contact.bodyPart] ?? contact.bodyPart;
      const surfaceLabel = ({ mattress: '床面', seat: '座面', handle: '把手', 'interaction-point': '交互点', ground: '地面' })[contact.surface];
      issues.push({ level: 'error', path: `contacts.${index}.bodyPart`, message: `${partLabel}不能与${surfaceLabel}建立当前类型的接触关系` });
    }
    const hasActionIndex = contact.actionIndex !== undefined;
    const indexedAction = hasActionIndex ? plan.actions[contact.actionIndex!] : undefined;
    if (hasActionIndex && (!Number.isInteger(contact.actionIndex) || !indexedAction)) {
      issues.push({ level: 'error', path: `contacts.${index}.actionIndex`, message: `接触关系引用了不存在的动作阶段 ${contact.actionIndex}` });
    }
    const contactAction = hasActionIndex
      ? indexedAction
      : plan.actions.find((action) => action.template === contact.phase || action.clause.includes(contact.phase));
    if (!contactAction) {
      issues.push({ level: 'warning', path: `contacts.${index}.phase`, message: `接触阶段 ${contact.phase} 未对应到动作段` });
    } else {
      if (contactAction.template !== contact.phase && !contactAction.clause.includes(contact.phase)) {
        issues.push({ level: 'error', path: `contacts.${index}.actionIndex`, message: `接触关系标记为 ${contact.phase}，但绑定的是 ${contactAction.template} 阶段` });
      }
      if (isGround) {
        const groundedRecovery = contactAction.template === 'orient' && /翻身|侧身|侧卧/.test(contactAction.clause);
        const expectedRelation = contactAction.template === 'sleep' ? 'rest' : 'support';
        if (!['kneel', 'lie', 'sleep'].includes(contactAction.template) && !groundedRecovery) {
          issues.push({ level: 'error', path: `contacts.${index}.actionIndex`, message: `地面支撑只能绑定跪地、躺卧或睡眠阶段，当前为 ${contactAction.template}` });
        }
        if (contact.relation !== expectedRelation) {
          const phaseName = contactAction.template === 'sleep' ? '睡眠' : contactAction.template === 'kneel' ? '跪地下撑' : '躺卧';
          issues.push({ level: 'error', path: `contacts.${index}.relation`, message: `${phaseName}阶段的地面接触应为 ${expectedRelation}` });
        }
      }
      if (!isGround && contactAction.targetPropId !== contact.propId) {
        const actionTarget = contactAction.targetPropId ?? '未绑定目标';
        const explicitConflict = hasActionIndex && Boolean(contactAction.targetPropId);
        issues.push({
          level: explicitConflict ? 'error' : 'warning',
          path: `contacts.${index}.propId`,
          message: `接触目标 ${contact.propId} 与动作阶段目标 ${actionTarget} 不一致${explicitConflict ? '，请修正道具绑定' : ''}`,
        });
      }
      const expectedContacts: Record<string, { bodyParts: ContactConstraint['bodyPart'][]; relation: ContactConstraint['relation']; label: string }> = {
        sit: { bodyParts: ['pelvis'], relation: 'support', label: '坐下' },
        kneel: { bodyParts: ['hand', 'legs'], relation: 'support', label: '跪地' },
        lie: { bodyParts: ['pelvis', 'back', 'head', 'legs'], relation: 'support', label: '躺卧' },
        sleep: { bodyParts: ['head', 'legs', 'back'], relation: 'rest', label: '睡眠' },
        sword: { bodyParts: ['hand'], relation: 'support', label: '持剑' },
        handoff: { bodyParts: ['hand'], relation: 'support', label: '换手' },
      };
      const expectedContact = contactAction.template === 'orient' && /翻身|侧身|侧卧/.test(contactAction.clause)
        ? { bodyParts: ['hand'] as ContactConstraint['bodyPart'][], relation: 'support' as const, label: '侧身支撑' }
        : expectedContacts[contactAction.template];
      if (expectedContact) {
        if (!expectedContact.bodyParts.includes(contact.bodyPart)) {
          issues.push({ level: 'error', path: `contacts.${index}.bodyPart`, message: `${expectedContact.label}阶段不应使用${contact.bodyPart}作为主要接触部位` });
        }
        if (contact.relation !== expectedContact.relation) {
          issues.push({ level: 'error', path: `contacts.${index}.relation`, message: `${expectedContact.label}阶段的接触关系应为 ${expectedContact.relation}` });
        }
      }
    }
  }
  // Report missing semantic contacts as well as malformed ones. A plan can be
  // structurally valid while still omitting the support/interaction that makes
  // an action physically understandable to the preview renderer.
  for (const [actionIndex, action] of plan.actions.entries()) {
    const requiredContact = action.template === 'sit'
      || action.template === 'kneel'
      || action.template === 'lie'
      || action.template === 'sleep'
      || action.template === 'orient' && /翻身|侧身|侧卧/.test(action.clause)
      || action.template === 'reach' && Boolean(action.targetPropId)
      || (action.template === 'sword' || action.template === 'handoff') && propsById.get(action.targetPropId ?? '')?.kind === 'sword';
    if (!requiredContact) continue;
    const expectedPropId = action.targetPropId ?? (action.template === 'kneel' || action.template === 'lie' || action.template === 'sleep'
      || action.template === 'orient' && /翻身|侧身|侧卧/.test(action.clause) ? 'ground' : undefined);
    const hasContact = plan.contacts.some((contact) => {
      const sameStage = contact.actionIndex === actionIndex
        || contact.actionIndex === undefined && (contact.phase === action.template || action.clause.includes(contact.phase));
      return sameStage && (expectedPropId === undefined || contact.propId === expectedPropId);
    });
    if (!hasContact) {
      const targetLabel = expectedPropId ? `目标 ${expectedPropId}` : '明确支撑面';
      issues.push({ level: 'warning', path: `actions.${actionIndex}.contacts`, message: `动作 ${actionIndex + 1}（${action.template}）缺少与${targetLabel}对应的接触/支撑关系，预演无法确认该阶段如何完成` });
    }
  }
  for (const overflow of findStagePropRoomOverflows(plan.environment.props)) {
    issues.push({
      level: 'warning',
      path: `environment.props.${overflow.propId}`,
      message: `道具 ${overflow.propId} 的实体代理超出房间${overflow.axis === 'width' ? '宽度' : overflow.axis === 'length' ? '深度' : '净高'}约 ${(overflow.overflowMeters * 100).toFixed(0)} 厘米`,
    });
  }
  if (plan.target.propId && !propIds.has(plan.target.propId)) issues.push({ level: 'error', path: 'target.propId', message: '动作目标道具已从场景移除' });
  if (plan.target.distanceMeters !== undefined && (!Number.isFinite(plan.target.distanceMeters) || plan.target.distanceMeters < 0)) {
    issues.push({ level: 'error', path: 'target.distanceMeters', message: '动作目标距离必须是有限的非负数' });
  } else if (plan.target.distanceMeters !== undefined && plan.target.distanceMeters > 5) {
    issues.push({ level: 'warning', path: 'target.distanceMeters', message: '人物停靠点距目标超过 5 米，可能不符合本次交互需要' });
  }
  if (plan.target.obstructed) issues.push({ level: 'warning', path: 'target.obstructed', message: '目标直线路径与场景道具相交，需要调整场景或手动规划绕行' });
  const effectIds = new Set<string>();
  for (const [index, effect] of plan.effects.entries()) {
    if (typeof effect.id !== 'string' || !effect.id.trim() || effectIds.has(effect.id)) {
      issues.push({ level: 'error', path: `effects.${index}.id`, message: '特效 ID 必须非空且在当前方案中唯一' });
    }
    if (typeof effect.id === 'string') effectIds.add(effect.id);
    if (!Number.isFinite(effect.time) || effect.time < 0 || effect.time > plan.duration) issues.push({ level: 'error', path: `effects.${index}.time`, message: '特效触发时间超出预演时长' });
    if (!Number.isFinite(effect.duration) || effect.duration < 0.05 || effect.duration > 10) issues.push({ level: 'error', path: `effects.${index}.duration`, message: '特效持续时间必须在 0.05–10 秒之间' });
    else if (effect.time + effect.duration > plan.duration + 1e-3) issues.push({ level: 'warning', path: `effects.${index}.duration`, message: '特效持续时间超出片尾，会在预演结束时被截断' });
    if (!Number.isFinite(effect.scale) || effect.scale < 0.05 || effect.scale > 5) issues.push({ level: 'error', path: `effects.${index}.scale`, message: '特效大小必须在 0.05–5 之间' });
    if (!Array.isArray(effect.position) || effect.position.length !== 3
      || !effect.position.every((value) => Number.isFinite(value) && Math.abs(value) <= 100)) {
      issues.push({ level: 'error', path: `effects.${index}.position`, message: '特效位置必须是范围 -100 到 100 米内的有限三维坐标' });
    }
    if (!/^#[\da-f]{6}$/i.test(effect.color)) issues.push({ level: 'error', path: `effects.${index}.color`, message: '特效颜色必须是 #RRGGBB 格式' });
    const validPath = effect.path === undefined || (Array.isArray(effect.path) && effect.path.length >= 2 && effect.path.length <= 64
      && effect.path.every((point) => Array.isArray(point) && point.length === 3
        && point.every((value) => Number.isFinite(value) && Math.abs(value) <= 100)));
    const validBladeSweep = effect.bladeSweep === undefined || (Array.isArray(effect.bladeSweep) && effect.bladeSweep.length >= 2 && effect.bladeSweep.length <= 64
      && effect.bladeSweep.every((sample) => sample && [sample.base, sample.tip].every((point) => Array.isArray(point) && point.length === 3
        && point.every((value) => Number.isFinite(value) && Math.abs(value) <= 100))));
    if (!validPath) issues.push({ level: 'error', path: `effects.${index}.path`, message: '特效轨迹必须由 2–64 个范围 -100 到 100 米内的有限三维点组成' });
    if (effect.path && effect.kind !== 'slash') issues.push({ level: 'error', path: `effects.${index}.path`, message: '只有 slash 挥砍拖尾支持 path 轨迹' });
    if (!validBladeSweep) issues.push({ level: 'error', path: `effects.${index}.bladeSweep`, message: '剑身扫掠样本必须有 2–64 组范围 -100 到 100 米内的有限 base/tip 坐标' });
    if (effect.bladeSweep && effect.kind !== 'slash') issues.push({ level: 'error', path: `effects.${index}.bladeSweep`, message: '只有 slash 挥砍拖尾支持 bladeSweep' });
    if (effect.actionIndex !== undefined) {
      const action = plan.actions[effect.actionIndex];
      if (!Number.isInteger(effect.actionIndex) || !action) {
        issues.push({ level: 'error', path: `effects.${index}.actionIndex`, message: `特效 ${index + 1} 引用了不存在的动作段` });
      } else if (effect.time < action.t0 - 1e-3 || effect.time > action.t1 + 1e-3) {
        issues.push({ level: 'error', path: `effects.${index}.actionIndex`, message: `特效 ${index + 1} 触发时间不在关联动作段内` });
      }
    } else if (plan.actions.length > 0 && effect.time >= 0 && effect.time <= plan.duration) {
      issues.push({ level: 'warning', path: `effects.${index}.actionIndex`, message: `特效 ${index + 1} 尚未关联具体动作段` });
    }
    const effectActionIndex = effect.actionIndex ?? actionIndexAtTime(plan.actions, effect.time);
    const actionSwordId = effectActionIndex === undefined ? undefined : plan.actions[effectActionIndex]?.targetPropId;
    const swords = plan.environment.props.filter((prop) => prop.kind === 'sword');
    const activeSword = (actionSwordId ? swords.find((prop) => prop.id === actionSwordId) : undefined)
      ?? (swords.length === 1 ? swords[0] : undefined);
    const staticObstacles = plan.environment.props.filter((prop) => prop.kind !== 'room'
      && (prop.kind !== 'sword' || prop.id !== activeSword?.id && prop.attachTo === null));
    const intersectsObstacle = (start: number[], end: number[], prop: StageProp, padding: number) => prop.kind === 'sword'
      ? segmentIntersectsStaticSword(start, end, prop, padding)
      : segmentIntersectsPropBounds(start, end, prop, padding);
    if (effect.kind === 'slash' && validPath && effect.path && effect.path.length >= 2) {
      const obstacles = staticObstacles.filter((prop) => effect.path!.slice(1).some((point, pointIndex) =>
        intersectsObstacle(effect.path![pointIndex], point, prop, prop.kind === 'sword' ? 0.03 : 0.06)));
      if (obstacles.length > 0) {
        issues.push({ level: 'warning', path: `effects.${index}.path`, message: `剑尖采样路径可能穿过场景道具 ${obstacles.map((prop) => prop.id).join('、')}；当前按旋转包围盒近似检查` });
      }
    }
    if (effect.kind === 'slash' && validBladeSweep && effect.bladeSweep && effect.bladeSweep.length >= 2) {
      const padding = activeSword ? Math.max(0.02, Math.hypot(activeSword.size.width, activeSword.size.height) / 2) : 0.03;
      const bladeFractions = [0, 0.25, 0.5, 0.75, 1];
      const pointAt = (sample: NonNullable<typeof effect.bladeSweep>[number], fraction: number) => sample.base.map((value, axis) =>
        value + (sample.tip[axis] - value) * fraction);
      const obstacles = staticObstacles.filter((prop) => bladeFractions.some((fraction) => effect.bladeSweep!.slice(1).some((sample, sampleIndex) =>
          intersectsObstacle(pointAt(effect.bladeSweep![sampleIndex], fraction), pointAt(sample, fraction), prop, padding))
          || effect.bladeSweep!.some((sample) => bladeFractions.slice(1).some((nextFraction, fractionIndex) =>
            intersectsObstacle(pointAt(sample, bladeFractions[fractionIndex]), pointAt(sample, nextFraction), prop, padding)))));
      if (obstacles.length > 0) {
        issues.push({ level: 'warning', path: `effects.${index}.bladeSweep`, message: `剑身扫掠采样网格可能穿过场景道具 ${obstacles.map((prop) => prop.id).join('、')}；当前是离散线段/包围盒近似，不代表连续碰撞或命中判定` });
      }
    }
  }
  const cameraTimes: number[] = [];
  for (const [index, key] of plan.camera.keyframes.entries()) {
    if (!Number.isFinite(key.time) || key.time < 0 || key.time > plan.duration) issues.push({ level: 'error', path: `camera.keyframes.${index}.time`, message: '镜头关键帧时间必须在预演时长内' });
    if (Number.isFinite(key.time) && cameraTimes.some((time) => Math.abs(time - key.time) < 1e-4)) {
      issues.push({ level: 'error', path: `camera.keyframes.${index}.time`, message: `镜头在 ${key.time.toFixed(2)} 秒有重复关键帧` });
    }
    if (Number.isFinite(key.time)) cameraTimes.push(key.time);
    if (![...key.position, ...key.target, key.fov].every(Number.isFinite) || key.fov < 15 || key.fov > 100) {
      issues.push({ level: 'error', path: `camera.keyframes.${index}`, message: '镜头位置、目标点或视角范围无效' });
    } else if (Math.hypot(key.position[0] - key.target[0], key.position[1] - key.target[1], key.position[2] - key.target[2]) < 0.01) {
      issues.push({ level: 'error', path: `camera.keyframes.${index}.direction`, message: '镜头位置和注视点不能重合或相距不足 1 厘米' });
    }
  }
  if (plan.camera.enabled) {
    const cameraKeys = plan.camera.keyframes.filter((key) => Number.isFinite(key.time) && key.time >= 0 && key.time <= plan.duration)
      .sort((a, b) => a.time - b.time);
    if (cameraKeys.length === 0) {
      issues.push({ level: 'warning', path: 'camera.keyframes', message: '镜头轨道已启用但没有有效关键帧，播放时会保留视口默认机位' });
    } else {
      const first = cameraKeys[0].time;
      const last = cameraKeys.at(-1)!.time;
      const uncovered: string[] = [];
      if (first > 1e-3) uncovered.push(`片头 ${first.toFixed(2)} 秒`);
      if (last < plan.duration - 1e-3) uncovered.push(`片尾 ${Math.max(0, plan.duration - last).toFixed(2)} 秒`);
      if (uncovered.length > 0) {
        issues.push({ level: 'warning', path: 'camera.coverage', message: `镜头轨道未覆盖${uncovered.join('和')}，播放时会保持端点机位` });
      }
    }
  }
  for (const [index, event] of plan.events.entries()) {
    const action = plan.actions[event.actionIndex];
    if (!Number.isFinite(event.time) || event.time < 0 || event.time > plan.duration) issues.push({ level: 'error', path: `events.${index}.time`, message: `事件 ${index + 1} 时间超出预演时长` });
    if (typeof event.label !== 'string' || !event.label.trim()) issues.push({ level: 'error', path: `events.${index}.label`, message: `事件 ${index + 1} 缺少说明` });
    if (!Number.isInteger(event.actionIndex) || !action) issues.push({ level: 'error', path: `events.${index}.actionIndex`, message: `事件 ${index + 1} 引用了不存在的动作段` });
    else if (event.time < action.t0 - 1e-3 || event.time > action.t1 + 1e-3) issues.push({ level: 'warning', path: `events.${index}.time`, message: `事件 ${index + 1} 时间不在所关联动作阶段内` });
  }
  return issues;
}

/** Apply AI edits only to unlocked top-level fields; preserve manual locks and scene identity. */
export function applyScenePlanPatch(plan: ScenePlan, patch: Partial<ScenePlan>): ScenePlan {
  const locked = new Set(plan.lockedFields);
  const next = structuredClone(plan);
  for (const [key, value] of Object.entries(patch) as Array<[keyof ScenePlan, ScenePlan[keyof ScenePlan]]>) {
    if (key === 'version' || key === 'animationId' || key === 'lockedFields' || locked.has(key)) continue;
    (next as unknown as Record<string, unknown>)[key] = structuredClone(value);
  }
  return next;
}
