import type { AnimationData } from '../animation/types';
import type { CharacterMeta } from '../../types/global';
import type { SkeletonSnapshot } from '../skeleton/types';
import type { CameraKeyframe } from '../camera/track';
import type { StageProp } from '../previs/world';
import type { PrevisEffectEvent } from '../previs/effects';
import type { ActionPrevisData } from '../../stores/previsStore';
import type { SketchDraftData } from '../rig/sketchToSpec';

// P1 冻结 project schema v1（Save/Open UI 在 P4）。
export interface ProjectV1 {
  version: '1.0';
  character: CharacterMeta | null;
  sketchDraft?: SketchDraftData | null;
  skeleton: SkeletonSnapshot | null;
  animations: AnimationData[];
  activeAnimationId?: string | null;
  previs?: Record<string, ActionPrevisData>;
  scene: { bg: string; grid: boolean; shadows: boolean; props?: StageProp[]; effects?: PrevisEffectEvent[] };
  camera: { position: [number, number, number]; target: [number, number, number]; fov: number; keyframes?: CameraKeyframe[]; enabled?: boolean; autoGenerated?: boolean };
  settings: { fps: 30 | 60; loop: boolean };
  /**
   * PBR 材质覆盖（按材质路径存，不是 uuid —— uuid 存取后就变）。
   * 重新打开项目时在 GLB 加载完成后叠加。
   */
  materialOverrides?: Record<string, unknown>;
}

export function createEmptyProject(): ProjectV1 {
  return {
    version: '1.0',
    character: null,
    skeleton: null,
    animations: [],
    previs: {},
    scene: { bg: '#0b0d12', grid: true, shadows: true, props: [] },
    camera: { position: [2.5, 1.8, 3.2], target: [0, 1, 0], fov: 45 },
    settings: { fps: 30, loop: true },
  };
}

export function validateProject(p: ProjectV1): string[] {
  const errors: string[] = [];
  if (p.version !== '1.0') errors.push(`unsupported version ${p.version}`);
  if (p.activeAnimationId && !p.animations.some((animation) => animation.id === p.activeAnimationId)) errors.push('activeAnimationId must reference an animation in the project');
  return errors;
}
