import * as THREE from 'three';
import { useAnimationStore } from '../../stores/animationStore';
import { usePrevisStore } from '../../stores/previsStore';
import { useCharacterStore } from '../../stores/characterStore';
import { useIKStore } from '../../stores/ikStore';
import { useSelectionStore } from '../../stores/selectionStore';
import { useSkeletonStore } from '../../stores/skeletonStore';
import { useWorldStore } from '../../stores/worldStore';
import { captureBoneLocal, indexBonesByName } from '../../core/animation/applyPose';
import { solvePinsLive } from '../../core/ik/applyPoseWithIK';
import type { IKChainId } from '../../core/ik/types';
import { MockMotionProvider } from '../motion/MockMotionProvider';
import { HttpMotionProvider } from '../motion/HttpMotionProvider';
import { buildBoneMap, buildRestMap, buildRestPositionMap, generatePlannedTracks, isKnownTemplate, type PlanSegment } from '../motion/procedural';
import { MathInbetweenProvider } from '../inbetween/MathInbetweenProvider';
import { applyAIPreviewSuggestions } from '../motion/aiSuggestions';
import { analyzeTrajectory, JOINT_LIMIT_DEGREES } from '../../core/physics/analyze';
import { collectTrajectory } from '../../core/physics/trajectory';
import { formatMotionCollisionWarnings, inspectGroundSupportWarnings, inspectMotionCollisions, inspectPropSupportWarnings, isMotionCollisionWarning } from '../../core/previs/collision';
import { reconcileContactsToActions } from '../../core/previs/contacts';
import { bakeDoorHandleContacts } from '../../core/previs/doorContact';
import { correctGroundedLegTracks } from '../../core/previs/groundContactCorrection';
import { inspectCameraSubjectFraming } from '../../core/previs/cameraFraming';
import { buildBalanceCorrectionEntries, buildFootLockEntries, buildHipsLiftEntries, buildJointLimitEntries, buildSmoothedHipsEntries } from '../../core/physics/fixes';
import type { QuatTuple, Vec3Tuple } from '../../types/global';
import { ambiguousScenePropIds, decomposeSceneAction, defaultInteractionDistance, defaultStagePropPosition, estimateCharacterHeight, estimateGroundHipLocalOffset, findStagePropOverlaps, findStagePropRoomOverflows, resolveBedInteractionFrame, resolvePropInteractionFrame, resolveSequentialInteractionFrames, STAGE_PROP_SIZE_LIMITS } from '../../core/previs/world';
import { createScenePlan } from '../../core/previs/scenePlan';
import { listMorphTargets } from '../../core/face/morphs';
import { useCameraStore } from '../../stores/cameraStore';
import { useEffectsStore } from '../../stores/effectsStore';
import { useMotionStore } from '../../stores/motionStore';
import type { AnimationData, BoneTrack } from '../../core/animation/types';
import type { StageProp } from '../../core/previs/world';
import { actionIndexAtTime, type BladeSweepSample, type PrevisEffectEvent, type PrevisEffectKind } from '../../core/previs/effects';
import { normalizePlan, validatePlan } from '../../core/previs/plan';
import type { AgentAction, ToolName, ToolResult } from './toolTypes';
import { isToolName } from './toolTypes';

const mockMotion = new MockMotionProvider();
const mathInbetween = new MathInbetweenProvider();

function syncScenePlanSnapshot() {
  const anims = useAnimationStore.getState().animations;
  usePrevisStore.getState().syncEditorContext(
    useWorldStore.getState().props,
    useEffectsStore.getState().events,
    useCameraStore.getState().keyframes,
    Object.fromEntries(anims.map((animation) => [animation.id, animation.duration])),
    useAnimationStore.getState().activeId,
    useCameraStore.getState().enabled,
    useCameraStore.getState().autoGenerated,
  );
}

function rebuildBoundTargetPositionTrack(
  animation: AnimationData,
  propId: string,
  segments: PlanSegment[],
  props: StageProp[],
  scene: THREE.Group,
  snapshot: NonNullable<ReturnType<typeof useSkeletonStore.getState>['snapshot']>,
  targetDistance?: number,
): { tracks: BoneTrack[]; warnings: string[] } | null {
  const movementTemplates = new Set(['march', 'orient', 'sit', 'lie', 'sleep', 'reach', 'stand']);
  const ranges = segments.filter((segment) => segment.targetPropId === propId && movementTemplates.has(segment.template));
  if (ranges.length === 0) return null;

  const segmentInteractions = resolveSequentialInteractionFrames(segments, scene, snapshot, props,
    targetDistance === undefined ? undefined : { [propId]: targetDistance });
  const generated = generatePlannedTracks(buildBoneMap(snapshot), segments, animation.duration, 7,
    buildRestMap(snapshot), buildRestPositionMap(snapshot), null, {}, segmentInteractions,
    props.find((prop) => prop.kind === 'room')?.position[1] ?? 0,
    estimateGroundHipLocalOffset(scene, snapshot, props.find((prop) => prop.kind === 'room')?.position[1] ?? 0));
  const hipsName = buildBoneMap(snapshot).hips;
  if (!hipsName) return { tracks: animation.tracks, warnings: ['骨架未映射 hips，无法根据新道具位置重算走位轨道'] };
  const oldTrack = animation.tracks.find((track) => track.boneName === hipsName);
  const generatedTrack = generated.tracks.find((track) => track.boneName === hipsName);
  if (!generatedTrack?.position.length) return { tracks: animation.tracks, warnings: ['动作 Provider 未生成髋部位置轨道，场景目标已更新但走位未重算'] };
  const inAffectedRange = (time: number) => ranges.some((range) => time >= range.t0 - 1e-4 && time <= range.t1 + 1e-4);
  const byTime = new Map<number, BoneTrack['position'][number]>();
  for (const key of oldTrack?.position ?? []) if (!inAffectedRange(key.time)) byTime.set(key.time, key);
  for (const key of generatedTrack.position) if (inAffectedRange(key.time)) byTime.set(key.time, key);
  if (![...byTime.keys()].some((time) => ranges.some((range) => time >= range.t0 - 1e-4 && time <= range.t1 + 1e-4))) {
    return { tracks: animation.tracks, warnings: ['新场景目标没有可用的走位关键帧，原动画保持不变'] };
  }
  const position = [...byTime.values()].sort((a, b) => a.time - b.time);
  const nextTrack: BoneTrack = oldTrack
    ? { ...oldTrack, position }
    : { boneName: hipsName, position, rotation: [], scale: [] };
  return {
    tracks: oldTrack
      ? animation.tracks.map((track) => track === oldTrack ? nextTrack : track)
      : [...animation.tracks, nextTrack],
    warnings: generated.warnings,
  };
}

function isPlanFieldLocked(field: string): boolean {
  const animation = needAnim();
  return Boolean(animation && usePrevisStore.getState().byAnimationId[animation.id]?.scenePlan?.lockedFields.includes(field));
}

function motionGenerationContextKey(character: THREE.Group | null): string {
  const animationState = useAnimationStore.getState();
  const animation = animationState.animations.find((item) => item.id === animationState.activeId);
  const activePlan = animationState.activeId
    ? usePrevisStore.getState().byAnimationId[animationState.activeId]?.scenePlan
    : undefined;
  character?.updateWorldMatrix(true, false);
  const camera = useCameraStore.getState();
  const motionConfig = useMotionStore.getState();
  return JSON.stringify({
    activeId: animationState.activeId,
    animation,
    pausedCursor: animationState.playing ? null : animationState.currentTime,
    characterId: character?.uuid,
    characterWorldMatrix: character?.matrixWorld.toArray(),
    skeleton: useSkeletonStore.getState().snapshot,
    props: useWorldStore.getState().props,
    activePlan: activePlan ? {
      actions: activePlan.actions,
      contacts: activePlan.contacts,
      effects: activePlan.effects,
      events: activePlan.events,
      lockedFields: activePlan.lockedFields,
      target: activePlan.target,
      weapons: activePlan.weapons,
    } : undefined,
    camera: { enabled: camera.enabled, autoGenerated: camera.autoGenerated, keyframes: camera.keyframes },
    motionProvider: { providerId: motionConfig.providerId, baseUrl: motionConfig.baseUrl },
  });
}

function clauseOverlap(left: string, right: string): number {
  const bigrams = (value: string) => {
    const text = Array.from(value.toLowerCase().replace(/\s+/g, ''));
    return new Set(text.slice(0, -1).map((char, index) => `${char}${text[index + 1]}`));
  };
  const a = bigrams(left);
  const b = bigrams(right);
  if (a.size === 0 || b.size === 0) return 0;
  let shared = 0;
  for (const token of a) if (b.has(token)) shared += 1;
  return shared / (a.size + b.size - shared);
}

/** Carry rule-derived prop targets across LLM-inserted phases without relying on array indexes. */
function alignRuleSegments(
  modelSegments: PlanSegment[],
  ruleSegments: PlanSegment[],
  ambiguousPropIds: Set<string>,
  duration: number,
  completeMissing = false,
): { segments: PlanSegment[]; ruleToModel: Map<number, number>; restoredRuleSegments: PlanSegment[] } {
  const result = modelSegments.map((segment) => ({ ...segment }));
  const ruleToModel = new Map<number, number>();
  for (const segment of result) if (segment.targetPropId && ambiguousPropIds.has(segment.targetPropId)) delete segment.targetPropId;
  const rows = ruleSegments.length + 1;
  const columns = modelSegments.length + 1;
  const score = Array.from({ length: rows }, () => Array<number>(columns).fill(0));
  const matchScore = (rule: PlanSegment, model: PlanSegment) => rule.template === model.template
    ? 1000 + Math.round(clauseOverlap(rule.clause, model.clause) * 20)
    : Number.NEGATIVE_INFINITY;
  for (let i = ruleSegments.length - 1; i >= 0; i--) {
    for (let j = modelSegments.length - 1; j >= 0; j--) {
      score[i][j] = Math.max(
        score[i + 1][j],
        score[i][j + 1],
        matchScore(ruleSegments[i], modelSegments[j]) + score[i + 1][j + 1],
      );
    }
  }

  let i = 0;
  let j = 0;
  while (i < ruleSegments.length && j < modelSegments.length) {
    const matched = matchScore(ruleSegments[i], modelSegments[j]) + score[i + 1][j + 1];
    if (Number.isFinite(matched) && score[i][j] === matched) {
      ruleToModel.set(i, j);
      const targetPropId = ruleSegments[i].targetPropId;
      if (targetPropId && !ambiguousPropIds.has(targetPropId) && !result[j].targetPropId) result[j].targetPropId = targetPropId;
      i += 1;
      j += 1;
    } else if (score[i + 1][j] > score[i][j + 1]) i += 1;
    else j += 1;
  }
  const restoredRuleSegments: PlanSegment[] = [];
  if (completeMissing && ruleToModel.size > 0 && ruleToModel.size < ruleSegments.length) {
    const insertBefore = Array.from({ length: result.length + 1 }, () => [] as PlanSegment[]);
    for (let ruleIndex = 0; ruleIndex < ruleSegments.length; ruleIndex++) {
      if (ruleToModel.has(ruleIndex)) continue;
      let nextModelIndex: number | undefined;
      for (let next = ruleIndex + 1; next < ruleSegments.length; next++) {
        nextModelIndex = ruleToModel.get(next);
        if (nextModelIndex !== undefined) break;
      }
      if (nextModelIndex === undefined) {
        for (let previous = ruleIndex - 1; previous >= 0; previous--) {
          const previousModelIndex = ruleToModel.get(previous);
          if (previousModelIndex !== undefined) {
            nextModelIndex = previousModelIndex + 1;
            break;
          }
        }
      }
      const fallback = { ...ruleSegments[ruleIndex] };
      if (fallback.targetPropId && ambiguousPropIds.has(fallback.targetPropId)) delete fallback.targetPropId;
      insertBefore[nextModelIndex ?? result.length].push(fallback);
      restoredRuleSegments.push(fallback);
    }

    const ordered: PlanSegment[] = [];
    for (let index = 0; index <= result.length; index++) {
      ordered.push(...insertBefore[index]);
      if (index < result.length) ordered.push(result[index]);
    }
    const weights = ordered.map((segment) => Math.max(0.1, segment.t1 - segment.t0));
    const totalWeight = weights.reduce((total, weight) => total + weight, 0);
    let time = 0;
    const completed = ordered.map((segment, index) => {
      const t0 = time;
      time = index === ordered.length - 1 ? duration : time + duration * weights[index] / totalWeight;
      return { ...segment, t0, t1: time };
    });
    const remapped = alignRuleSegments(completed, ruleSegments, ambiguousPropIds, duration);
    return { ...remapped, restoredRuleSegments };
  }
  return { segments: result, ruleToModel, restoredRuleSegments };
}

/* ---------- 参数校验（手写严格校验，不引入 zod 依赖） ---------- */

function err(code: string, message: string): ToolResult {
  return { ok: false, error: { code, message } };
}

function normalizeMotionTemplate(template: unknown): unknown {
  if (typeof template !== 'string') return template;
  const value = template.trim().toLowerCase();
  const aliases: Record<string, string> = {
    walk: 'march',
    turn_right_head: 'look_right',
    head_turn_right: 'look_right',
    turn_head_right: 'look_right',
    look_right_head: 'look_right',
    turn_left_head: 'look_left',
    head_turn_left: 'look_left',
    turn_head_left: 'look_left',
    look_left_head: 'look_left',
  };
  return aliases[value] ?? value;
}

function reqStr(args: Record<string, unknown>, key: string): string | null {
  const v = args[key];
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function optStr(args: Record<string, unknown>, key: string): string | undefined {
  const v = args[key];
  return typeof v === 'string' ? v : undefined;
}

function stringList(value: unknown): string[] {
  const values = Array.isArray(value) ? value : typeof value === 'string' ? [value] : [];
  return values.filter((item): item is string => typeof item === 'string' && item.trim().length > 0).slice(0, 8);
}

function reqNum(args: Record<string, unknown>, key: string): number | null {
  const v = args[key];
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}

function optNum(args: Record<string, unknown>, key: string, fallback: number): number {
  const v = args[key];
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}

function reqVec3(args: Record<string, unknown>, key: string): Vec3Tuple | null {
  const v = args[key];
  if (!Array.isArray(v) || v.length !== 3) return null;
  const n = (v as unknown[]).map(Number);
  if (n.some((x) => !Number.isFinite(x) || Math.abs(x) > 100)) return null;
  return [n[0], n[1], n[2]];
}

function optVec3(args: Record<string, unknown>, key: string): Vec3Tuple | undefined {
  if (args[key] === undefined) return undefined;
  return reqVec3(args, key) ?? undefined;
}

/** 骨骼引用：精确名 → 语义（大小写不敏感，如 upperarm.l）→ null */
function resolveBone(scene: THREE.Object3D, ref: string): THREE.Bone | null {
  const bones = indexBonesByName(scene);
  if (bones.has(ref)) return bones.get(ref)!;
  const snap = useSkeletonStore.getState().snapshot;
  if (snap) {
    const lower = ref.toLowerCase();
    const node = Object.values(snap.nodes).find(
      (n) => n.name === ref || (n.semantic && n.semantic.toLowerCase() === lower),
    );
    if (node) {
      const b = bones.get(node.name);
      if (b) return b;
    }
  }
  return null;
}

function boneIdOf(name: string): string | null {
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return null;
  const node = Object.values(snap.nodes).find((n) => n.name === name);
  return node ? node.id : null;
}

function needScene(): THREE.Group | ToolResult {
  const so = useCharacterStore.getState().sceneObject;
  return so ?? err('NO_CHARACTER', '未加载角色，请先拖入 GLB');
}

function needAnim() {
  const st = useAnimationStore.getState();
  const a = st.active();
  return a ?? null;
}

/* ---------- 工具实现 ---------- */

async function inspectSkeleton(args: Record<string, unknown>): Promise<ToolResult> {
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return err('NO_CHARACTER', '未加载角色');
  const q = optStr(args, 'query')?.toLowerCase();
  const bones = Object.values(snap.nodes)
    .filter((n) => (!q || n.name.toLowerCase().includes(q)) && true)
    .map((n) => ({ name: n.name, semantic: n.semantic, parent: n.parent ? snap.nodes[n.parent]?.name ?? null : null }));
  return { ok: true, data: { boneCount: snap.boneCount, matched: bones.length, bones: bones.slice(0, 120) } };
}

async function selectBone(args: Record<string, unknown>): Promise<ToolResult> {
  const ref = reqStr(args, 'bone');
  if (!ref) return err('BAD_ARGS', 'select_bone 需要 bone（名或语义）');
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const b = resolveBone(scene, ref);
  if (!b) return err('BONE_NOT_FOUND', `找不到骨骼 ${ref}`);
  const id = boneIdOf(b.name);
  useSelectionStore.getState().select(id);
  return { ok: true, data: { name: b.name, id } };
}

async function modifyBone(args: Record<string, unknown>): Promise<ToolResult> {
  const ref = reqStr(args, 'bone');
  if (!ref) return err('BAD_ARGS', 'modify_bone 需要 bone');
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const b = resolveBone(scene, ref);
  if (!b) return err('BONE_NOT_FOUND', `找不到骨骼 ${ref}`);

  const absE = reqVec3(args, 'rotationEulerDeg');
  const deltaE = reqVec3(args, 'rotationDeltaDeg');
  const absP = reqVec3(args, 'position');
  const deltaP = reqVec3(args, 'positionDelta');
  if (!absE && !deltaE && !absP && !deltaP) {
    return err('BAD_ARGS', 'modify_bone 需要 rotationEulerDeg / rotationDeltaDeg / position / positionDelta 之一');
  }
  if (absE) {
    b.quaternion.setFromEuler(
      new THREE.Euler(THREE.MathUtils.degToRad(absE[0]), THREE.MathUtils.degToRad(absE[1]), THREE.MathUtils.degToRad(absE[2]), 'XYZ'),
    );
  }
  if (deltaE) {
    const q = new THREE.Quaternion().setFromEuler(
      new THREE.Euler(THREE.MathUtils.degToRad(deltaE[0]), THREE.MathUtils.degToRad(deltaE[1]), THREE.MathUtils.degToRad(deltaE[2]), 'XYZ'),
    );
    b.quaternion.multiply(q);
  }
  if (absP) b.position.fromArray(absP);
  if (deltaP) b.position.set(b.position.x + deltaP[0], b.position.y + deltaP[1], b.position.z + deltaP[2]);
  scene.updateWorldMatrix(true, true);
  return { ok: true, data: { bone: b.name, quaternion: [b.quaternion.x, b.quaternion.y, b.quaternion.z, b.quaternion.w] as QuatTuple } };
}

async function createKeyframe(args: Record<string, unknown>): Promise<ToolResult> {
  const ref = reqStr(args, 'bone');
  if (!ref) return err('BAD_ARGS', 'create_keyframe 需要 bone');
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const b = resolveBone(scene, ref);
  if (!b) return err('BONE_NOT_FOUND', `找不到骨骼 ${ref}`);
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动动画，先 create_animation');
  const interp = optStr(args, 'interp');
  if (interp !== undefined && interp !== 'linear' && interp !== 'step') {
    return err('BAD_ARGS', 'interp 仅支持 linear/step');
  }
  const cap = captureBoneLocal(scene, b.name);
  if (!cap) return err('BONE_NOT_FOUND', `读取 ${b.name} 失败`);
  const time = optNum(args, 'time', useAnimationStore.getState().currentTime);
  const includePosition = args['includePosition'] === true;
  useAnimationStore.getState().bakePoseKeys(
    [{ boneName: b.name, time, value: cap.quaternion, interp: (interp ?? 'linear') as 'linear' | 'step' }],
    includePosition ? [{ boneName: b.name, time, value: cap.position }] : [],
  );
  return { ok: true, data: { bone: b.name, time } };
}

async function deleteKeyframe(args: Record<string, unknown>): Promise<ToolResult> {
  const ref = reqStr(args, 'bone');
  const time = reqNum(args, 'time');
  if (!ref || time === null) return err('BAD_ARGS', 'delete_keyframe 需要 bone + time');
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const b = resolveBone(scene, ref);
  if (!b) return err('BONE_NOT_FOUND', `找不到骨骼 ${ref}`);
  const ok = useAnimationStore.getState().deleteRotationKey(b.name, time);
  if (!ok) return err('KEY_NOT_FOUND', `${b.name} @${time}s 无关键帧`);
  return { ok: true, data: { bone: b.name, time } };
}

async function createAnimation(args: Record<string, unknown>): Promise<ToolResult> {
  const name = optStr(args, 'name') ?? 'Take';
  const id = useAnimationStore.getState().createAnimation(name.slice(0, 64));
  return { ok: true, data: { id, name } };
}

async function generateMotion(args: Record<string, unknown>): Promise<ToolResult> {
  const prompt = reqStr(args, 'prompt');
  if (!prompt) return err('BAD_ARGS', 'generate_motion 需要 prompt');
  const clarification = optStr(args, 'clarification')?.trim();
  if (clarification && clarification.length > 1000) return err('BAD_ARGS', 'clarification 不能超过 1000 字');
  const planningPrompt = clarification ? `${prompt}，用户澄清：${clarification}` : prompt;
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return err('NO_CHARACTER', '未加载角色');
  const defaultDuration = /睡|躺|卧/.test(prompt) ? 8 : 4;
  const segmentEnd = Array.isArray(args['segments'])
    ? Math.max(0, ...args['segments'].flatMap((segment) => typeof segment === 'object' && segment !== null
      && typeof (segment as Record<string, unknown>)['t1'] === 'number'
      && Number.isFinite((segment as Record<string, unknown>)['t1'])
      ? [(segment as Record<string, number>)['t1']] : []))
    : 0;
  const duration = Math.min(Math.max(optNum(args, 'duration', segmentEnd || defaultDuration), 0.5), 30);
  const rawInterpretation = typeof args['interpretation'] === 'object' && args['interpretation'] !== null
    ? args['interpretation'] as Record<string, unknown>
    : {};
  const requestedCertainty = rawInterpretation['certainty'] === 'high' || rawInterpretation['certainty'] === 'medium' || rawInterpretation['certainty'] === 'low'
    ? rawInterpretation['certainty'] as 'high' | 'medium' | 'low'
    : undefined;
  const interpretation = {
    ...(requestedCertainty ? { certainty: requestedCertainty } : {}),
    reasons: stringList(rawInterpretation['reasons']),
    questions: stringList(rawInterpretation['questions']),
    missingInfo: stringList(rawInterpretation['missingInfo']),
  };
  let plannedSegments: PlanSegment[] | undefined;
  if (args['segments'] !== undefined) {
    const rawSegments = args['segments'];
    if (!Array.isArray(rawSegments) || rawSegments.length === 0 || rawSegments.length > 24) return err('BAD_ARGS', 'segments 必须是 1–24 段的动作计划');
    const parsed: PlanSegment[] = [];
    for (const [index, raw] of rawSegments.entries()) {
      if (typeof raw !== 'object' || raw === null) return err('BAD_ARGS', `动作段 ${index + 1} 格式错误`);
      const segment = raw as Record<string, unknown>;
      const { t0, t1, template, clause, intensity, speed, targetPropId } = segment;
      const normalizedTemplate = normalizeMotionTemplate(template);
      if (typeof t0 !== 'number' || !Number.isFinite(t0) || typeof t1 !== 'number' || !Number.isFinite(t1)) {
        return err('BAD_ARGS', `动作段 ${index + 1} 的开始和结束时间必须是有限数字`);
      }
      if (typeof normalizedTemplate !== 'string' || !isKnownTemplate(normalizedTemplate)) {
        return err('BAD_ARGS', `动作段 ${index + 1} 的模板无效：${String(template)}`);
      }
      if (typeof clause !== 'string' || !clause.trim()) return err('BAD_ARGS', `动作段 ${index + 1} 缺少动作描述`);
      if (intensity !== undefined && (typeof intensity !== 'number' || !Number.isFinite(intensity) || intensity < 0.4 || intensity > 1.6)) {
        return err('BAD_ARGS', `动作段 ${index + 1} 的幅度须为 0.4–1.6`);
      }
      if (speed !== undefined && (typeof speed !== 'number' || !Number.isFinite(speed) || speed < 0.5 || speed > 2)) {
        return err('BAD_ARGS', `动作段 ${index + 1} 的速度须为 0.5–2`);
      }
      if (t0 < 0 || t1 > duration || t1 <= t0) return err('BAD_ARGS', `动作段 ${index + 1} 时间须在 0–${duration} 秒内且结束晚于开始`);
      if (targetPropId !== undefined && targetPropId !== null && (typeof targetPropId !== 'string' || !useWorldStore.getState().props.some((prop) => prop.id === targetPropId))) {
        return err('BAD_ARGS', `动作段 ${index + 1} 引用了不存在的场景道具`);
      }
      parsed.push({ t0, t1, template: normalizedTemplate, clause: clause.trim().slice(0, 200), ...(typeof intensity === 'number' ? { intensity } : {}), ...(typeof speed === 'number' ? { speed } : {}), ...(typeof targetPropId === 'string' ? { targetPropId } : {}) });
    }
    plannedSegments = normalizePlan(parsed, duration);
    const errors = validatePlan(plannedSegments, duration).filter((issue) => issue.level === 'error');
    if (errors.length > 0) return err('BAD_ARGS', errors.map((issue) => issue.message).join('；'));
  }
  try {
    const stageProps = useWorldStore.getState().props;
    const sceneObject = useCharacterStore.getState().sceneObject;
    if (!sceneObject) return err('NO_CHARACTER', '骨架数据仍在，但当前角色模型未载入；请重新载入角色后生成动作');
    const actor = { position: [sceneObject.position.x, sceneObject.position.y, sceneObject.position.z] as [number, number, number], forward: [Math.sin(sceneObject.rotation.y), Math.cos(sceneObject.rotation.y)] as [number, number] };
    const ambiguousPropIds = new Set(ambiguousScenePropIds(planningPrompt, stageProps, actor));
    const plan = decomposeSceneAction(planningPrompt, duration, stageProps, actor);
    const target = plan?.targetPropId ? stageProps.find((prop) => prop.id === plan.targetPropId) : undefined;
    const bedInteraction = target && sceneObject
      ? target.kind === 'bed' ? resolveBedInteractionFrame(target, sceneObject, snap, stageProps) : resolvePropInteractionFrame(target, sceneObject, snap, stageProps)
      : null;
    const requiresMissingBedClarification = plan?.warnings.some((warning) => /描述明确要求床面支撑/.test(warning)) ?? false;
    const planningAlignment = plannedSegments && !requiresMissingBedClarification
      ? alignRuleSegments(plannedSegments, plan?.segments ?? [], ambiguousPropIds, duration, true)
      : undefined;
    const motionSegments = requiresMissingBedClarification
      ? plan?.segments
      : plannedSegments
      ? planningAlignment?.segments
      : plan?.segments;
    const restoredStages = planningAlignment?.restoredRuleSegments ?? [];
    const restoredStageWarnings = restoredStages.length > 0
      ? [`模型漏掉了明确动作阶段，已按规则补入：${restoredStages.map((segment) => segment.clause).join('、')}`]
      : [];
    const worldInteractions = Object.fromEntries([...new Set((motionSegments ?? []).flatMap((segment) => segment.targetPropId ? [segment.targetPropId] : []))]
      .flatMap((propId) => {
        const prop = stageProps.find((item) => item.id === propId);
        if (!prop || !sceneObject) return [];
        const frame = prop.kind === 'bed'
          ? resolveBedInteractionFrame(prop, sceneObject, snap, stageProps)
          : resolvePropInteractionFrame(prop, sceneObject, snap, stageProps);
        return frame ? [[propId, frame] as const] : [];
      }));
    const segmentInteractions = sceneObject && motionSegments
      ? resolveSequentialInteractionFrames(motionSegments, sceneObject, snap, stageProps)
      : {};
    const planner = optStr(args, '_planner') === 'llm'
      ? { source: 'llm' as const, model: optStr(args, '_plannerModel') }
      : undefined;
    const contextKey = motionGenerationContextKey(sceneObject);
    const motionConfig = useMotionStore.getState();
    const motionProvider = motionConfig.providerId === 'http' ? new HttpMotionProvider(motionConfig.baseUrl) : mockMotion;
    const groundY = stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0;
    const r = await motionProvider.generateMotion({ prompt: planningPrompt, skeleton: snap, duration, fps: 30, stageProps, bedInteraction, worldInteractions, segmentInteractions, plannedSegments: motionSegments, planner,
      groundHipLocalOffset: estimateGroundHipLocalOffset(sceneObject, snap, groundY) });
    if (motionGenerationContextKey(useCharacterStore.getState().sceneObject) !== contextKey) {
      return err('STALE_CONTEXT', '等待动作生成期间角色、场景或当前动画已变化；为保护最新编辑，本次结果未应用，请重新生成');
    }
    const live = indexBonesByName(sceneObject);
    const unbound = [...new Set(r.animation.tracks.map((track) => track.boneName))].filter((name) => !live.has(name));
    if (r.animation.tracks.length === 0) return err('EMPTY_MOTION', '动作 Provider 返回了空骨骼轨道；未创建不可播放的预演动画');
    if (unbound.length === r.animation.tracks.length) {
      return err('SKELETON_MISMATCH', `动作 Provider 返回的骨骼均未匹配当前角色：${unbound.slice(0, 8).join('、')}。请检查骨架映射后重试`);
    }
    const mappingWarnings = unbound.length > 0
      ? [`动作 Provider 有 ${unbound.length} 个骨骼轨道未匹配当前角色，不会播放：${unbound.slice(0, 8).join('、')}${unbound.length > 8 ? '…' : ''}`]
      : [];
    const id = useAnimationStore.getState().createAnimation(r.animation.name);
    useAnimationStore.setState((s) => {
      const anims = structuredClone(s.animations);
      const a = anims.find((x) => x.id === id);
      if (a) {
        a.duration = r.animation.duration;
        a.fps = r.animation.fps;
        a.tracks = structuredClone(r.animation.tracks);
      }
      // 生成结果立即成为当前可播放预演，避免用户以为命令没有生效。
      return { animations: anims, activeId: id, currentTime: 0, playing: true };
    });
    const outputAlignment = alignRuleSegments(r.meta.segments ?? motionSegments ?? [], plan?.segments ?? [], ambiguousPropIds, r.animation.duration);
    const resultSegments = outputAlignment.segments;
    const resultContacts = (r.meta.contacts ?? []).flatMap((contact) => {
      if (!plan?.segments.length) return [contact];
      const ruleIndex = contact.actionIndex ?? plan?.segments.findIndex((segment) =>
        segment.template === contact.phase && (!contact.propId || segment.targetPropId === contact.propId));
      if (ruleIndex === undefined || ruleIndex < 0) return [];
      const modelIndex = outputAlignment.ruleToModel.get(ruleIndex);
      if (modelIndex === undefined) return [];
      return [{ ...contact, actionIndex: modelIndex, phase: resultSegments[modelIndex].template }];
    });
    const unmappedContacts = (r.meta.contacts ?? []).length - resultContacts.length;
    const alignmentWarnings = unmappedContacts > 0
      ? [`${unmappedContacts} 条规则推导的接触关系未能匹配到模型动作段，已避免绑到错误阶段；请在动作方案中补充或调整接触关系`]
      : [];
    const groundedTracks = correctGroundedLegTracks(sceneObject, r.animation, buildBoneMap(snap), resultSegments, resultContacts, groundY);
    const groundedAnimation = { ...r.animation, tracks: groundedTracks };
    const doorContactBake = bakeDoorHandleContacts(sceneObject, groundedAnimation, snap, stageProps, resultSegments, resultContacts);
    const playableAnimation = doorContactBake.animation;
    if (playableAnimation !== r.animation) {
      useAnimationStore.setState((state) => ({
        animations: state.animations.map((animation) => animation.id === id ? { ...animation, tracks: structuredClone(playableAnimation.tracks) } : animation),
      }));
    }
    const collisionFindings = inspectMotionCollisions(sceneObject, playableAnimation, stageProps, resultSegments, resultContacts, snap);
    const collisionWarnings = formatMotionCollisionWarnings(collisionFindings, sceneObject);
    const suggestions = applyAIPreviewSuggestions({ animationId: id, duration: playableAnimation.duration, segments: resultSegments, prompt: planningPrompt, stageProps, character: sceneObject, skeleton: snap, animation: playableAnimation, collisionFindings });
    const groundSupportWarnings = inspectGroundSupportWarnings(sceneObject, playableAnimation, resultSegments, resultContacts,
      stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0);
    const propSupportWarnings = inspectPropSupportWarnings(sceneObject, playableAnimation, resultSegments, resultContacts, stageProps);
    const cameraState = useCameraStore.getState();
    const framingWarnings = cameraState.enabled
      ? inspectCameraSubjectFraming(sceneObject, playableAnimation, cameraState.keyframes, playableAnimation.duration) : [];
    const warnings = [...(r.meta.warnings ?? []), ...restoredStageWarnings, ...mappingWarnings, ...alignmentWarnings, ...suggestions, ...doorContactBake.warnings, ...collisionWarnings, ...groundSupportWarnings, ...propSupportWarnings, ...framingWarnings];
    const scenePlan = createScenePlan({
      animationId: id, prompt, duration: r.animation.duration,
      character: { id: useCharacterStore.getState().meta?.id, label: useCharacterStore.getState().meta?.fileName ?? '主角', heightMeters: estimateCharacterHeight(sceneObject) },
      source: optStr(args, '_planner') === 'llm' ? 'model' : 'rules',
      model: optStr(args, '_plannerModel'), props: stageProps,
      actions: resultSegments, contacts: resultContacts,
      effects: useEffectsStore.getState().events.filter((event) => event.animationId === id),
      cameraKeyframes: cameraState.keyframes,
      cameraEnabled: cameraState.enabled,
      cameraAutoGenerated: cameraState.autoGenerated,
      target: {
        ...(plan?.targetPropId ? { propId: plan.targetPropId } : {}),
        ...(target ? { distanceMeters: defaultInteractionDistance(target) } : {}),
        ...(bedInteraction?.pathObstructed && !bedInteraction.approachPath ? { obstructed: true } : {}),
      },
      warnings,
      interpretation,
    });
    usePrevisStore.getState().setActionPrevis(id, {
      prompt,
      segments: resultSegments,
      contacts: resultContacts,
      warnings,
      scenePlan,
    });
    return { ok: true, data: {
      animationId: id,
      tracks: r.animation.tracks.length,
      template: r.meta.template,
      warnings,
      contacts: resultContacts,
      unbound,
      motion: { provider: r.meta.provider, source: r.meta.source, planner: r.meta.planner, model: r.meta.model, quality: r.meta.quality },
    } };
  } catch (e) {
    return err('GENERATE_FAILED', e instanceof Error ? e.message : '生成失败');
  }
}

async function reviseActionSegment(args: Record<string, unknown>): Promise<ToolResult> {
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动预演动画');
  if (isPlanFieldLocked('actions')) return err('FIELD_LOCKED', '动作段已锁定；解锁后才能由 AI 修改');
  const index = reqNum(args, 'segmentIndex');
  const hasClause = Object.hasOwn(args, 'clause');
  const hasTemplate = Object.hasOwn(args, 'template');
  const hasIntensity = Object.hasOwn(args, 'intensity');
  const hasSpeed = Object.hasOwn(args, 'speed');
  const hasTarget = Object.hasOwn(args, 'targetPropId');
  const clause = args['clause'];
  const template = args['template'];
  const intensity = args['intensity'];
  const speed = args['speed'];
  if (index === null || !Number.isInteger(index) || index < 0
    || !(hasClause || hasTemplate || hasIntensity || hasSpeed || hasTarget)
    || (hasClause && (typeof clause !== 'string' || !clause.trim()))
    || (hasTemplate && (typeof template !== 'string' || !isKnownTemplate(template)))
    || (hasIntensity && (typeof intensity !== 'number' || !Number.isFinite(intensity) || intensity < 0.4 || intensity > 1.6))
    || (hasSpeed && (typeof speed !== 'number' || !Number.isFinite(speed) || speed < 0.5 || speed > 2))) {
    return err('BAD_ARGS', '需要有效的 segmentIndex，以及至少一个有效字段：clause、template、intensity（0.4–1.6）、speed（0.5–2）或 targetPropId');
  }
  const snapshot = useSkeletonStore.getState().snapshot;
  const source = usePrevisStore.getState().byAnimationId[anim.id];
  if (!snapshot || !source) return err('NO_PREVIS_PLAN', '当前动画没有可编辑的预演方案');
  if (index >= source.segments.length) return err('SEGMENT_NOT_FOUND', `当前预演只有 ${source.segments.length} 段动作`);
  const next = structuredClone(source.segments) as PlanSegment[];
  const previousContactCount = source.scenePlan?.contacts.length ?? source.contacts?.length ?? 0;
  const previousEffectCount = useEffectsStore.getState().events.filter((event) => event.animationId === anim.id && event.actionIndex === index).length;
  const old = next[index];
  const updated: PlanSegment = {
    ...old,
    ...(hasClause ? { clause: (clause as string).trim().slice(0, 200) } : {}),
    ...(hasTemplate ? { template: template as string } : {}),
    ...(hasIntensity ? { intensity: intensity as number } : {}),
    ...(hasSpeed ? { speed: speed as number } : {}),
  };
  const stageProps = useWorldStore.getState().props;
  if (Object.hasOwn(args, 'targetPropId')) {
    const targetPropId = args['targetPropId'];
    if (targetPropId !== null && (typeof targetPropId !== 'string' || !stageProps.some((prop) => prop.id === targetPropId))) {
      return err('BAD_ARGS', 'targetPropId 必须是当前场景中的道具 ID 或 null');
    }
    if (targetPropId === null || targetPropId === '') delete updated.targetPropId;
    else updated.targetPropId = targetPropId as string;
  }
  const actionTextChanged = updated.template !== old.template || updated.clause !== old.clause;
  const targetChanged = updated.targetPropId !== old.targetPropId;
  const contactBound = source.scenePlan?.contacts.some((contact) => {
    const sameAction = contact.actionIndex !== undefined
      ? contact.actionIndex === index
      : contact.phase === old.template || contact.phase === old.clause;
    if (!sameAction) return false;
    // Ground support contacts have no segment targetPropId, so match them by phase/index.
    return contact.actionIndex === index
      || contact.propId === old.targetPropId
      || contact.propId === updated.targetPropId
      || contact.propId === 'ground';
  });
  if (contactBound && (actionTextChanged || targetChanged) && isPlanFieldLocked('contacts')) {
    return err('FIELD_LOCKED', '该动作段关联了已锁定的接触关系；解锁接触后才能修改动作');
  }
  const eventBound = source.scenePlan?.events.some((event) => event.actionIndex === index);
  if (eventBound && actionTextChanged && isPlanFieldLocked('events')) {
    return err('FIELD_LOCKED', '该动作段关联了已锁定的事件；解锁事件后才能修改动作');
  }
  const effectBound = useEffectsStore.getState().events.some((event) => event.animationId === anim.id && event.actionIndex === index);
  if (effectBound && (updated.template !== old.template || targetChanged) && isPlanFieldLocked('effects')) {
    return err('FIELD_LOCKED', '该动作段关联了已锁定的特效；解锁特效后才能修改动作');
  }
  const targetIsSword = (propId?: string) => stageProps.some((prop) => prop.id === propId && prop.kind === 'sword');
  if ((old.template === 'sword' || updated.template === 'sword' || targetIsSword(old.targetPropId) || targetIsSword(updated.targetPropId))
    && (actionTextChanged || targetChanged) && isPlanFieldLocked('weapons')) {
    return err('FIELD_LOCKED', '武器已锁定；解锁武器字段后才能修改挥剑动作或目标');
  }
  next[index] = updated;
  const scene = useCharacterStore.getState().sceneObject;
  const target = source.scenePlan?.target.propId ? stageProps.find((prop) => prop.id === source.scenePlan?.target.propId) : undefined;
  const targetDistance = source.scenePlan?.target.distanceMeters;
  const bedInteraction = scene && target
    ? target.kind === 'bed'
      ? resolveBedInteractionFrame(target, scene, snapshot, stageProps, targetDistance)
      : resolvePropInteractionFrame(target, scene, snapshot, stageProps, targetDistance)
    : null;
  const worldInteractions = Object.fromEntries([...new Set(next.flatMap((segment) => segment.targetPropId ? [segment.targetPropId] : []))]
    .flatMap((propId) => {
      const prop = stageProps.find((item) => item.id === propId);
      if (!prop || !scene) return [];
      const distance = propId === source.scenePlan?.target.propId ? targetDistance : undefined;
      const frame = prop.kind === 'bed'
        ? resolveBedInteractionFrame(prop, scene, snapshot, stageProps, distance)
        : resolvePropInteractionFrame(prop, scene, snapshot, stageProps, distance);
      return frame ? [[propId, frame] as const] : [];
    }));
  try {
    const segmentInteractions = scene ? resolveSequentialInteractionFrames(next, scene, snapshot, stageProps,
      source.scenePlan?.target.propId ? { [source.scenePlan.target.propId]: targetDistance } : undefined) : {};
    const result = generatePlannedTracks(buildBoneMap(snapshot), next, anim.duration, 7, buildRestMap(snapshot), buildRestPositionMap(snapshot), bedInteraction, worldInteractions, segmentInteractions,
      stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0,
      scene ? estimateGroundHipLocalOffset(scene, snapshot, stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0) : undefined);
    const contacts = reconcileContactsToActions(source.segments, next, source.scenePlan?.contacts ?? source.contacts ?? []);
    const groundedTracks = scene
      ? correctGroundedLegTracks(scene, { ...anim, tracks: result.tracks }, buildBoneMap(snapshot), next, contacts,
        stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0)
      : result.tracks;
    let contactWarnings: string[] = [];
    let effectWarnings: string[] = [];
    let collisionWarnings: string[] = [];
    let groundSupportWarnings: string[] = [];
    let propSupportWarnings: string[] = [];
    let doorContactWarnings: string[] = [];
    const doorBake = scene ? bakeDoorHandleContacts(scene, { ...anim, tracks: groundedTracks }, snapshot, stageProps, next, contacts)
        : { animation: { ...anim, tracks: groundedTracks }, warnings: [] };
    doorContactWarnings = doorBake.warnings;
    collisionWarnings = scene ? formatMotionCollisionWarnings(inspectMotionCollisions(
      scene, doorBake.animation, stageProps, next, contacts, snapshot,
    ), scene) : [];
    groundSupportWarnings = scene ? inspectGroundSupportWarnings(scene, doorBake.animation, next,
      contacts, stageProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0) : [];
    propSupportWarnings = scene ? inspectPropSupportWarnings(scene, doorBake.animation, next, contacts, stageProps) : [];
    const routeWarnings = result.warnings.filter((warning) => /段走位(?:已绕开|没有可从当前起点)/.test(warning));
    // Save the pre-edit animation and editor context together before either plan or tracks change.
    useAnimationStore.getState().replaceActiveTracks(doorBake.animation.tracks);
    usePrevisStore.getState().updateSegments(anim.id, next);
    const latest = usePrevisStore.getState().byAnimationId[anim.id];
    if (latest) {
      const nextContactCount = latest.scenePlan?.contacts.length ?? latest.contacts?.length ?? 0;
      const nextEffectCount = useEffectsStore.getState().events.filter((event) => event.animationId === anim.id && event.actionIndex === index).length;
      contactWarnings = nextContactCount < previousContactCount
        ? [`动作段变化后已清除 ${previousContactCount - nextContactCount} 条不再匹配的接触关系；新动作若需要支撑或交互，请补充接触关系`]
        : [];
      effectWarnings = nextEffectCount < previousEffectCount
        ? [`动作段变化后已清除 ${previousEffectCount - nextEffectCount} 个不再匹配的特效；如仍需要请重新添加并绑定当前动作段`]
        : [];
      const warnings = [...new Set([
        ...(latest.warnings ?? []).filter((warning) => !/段走位(?:已绕开|没有可从当前起点)/.test(warning) && !isMotionCollisionWarning(warning) && !/(?:动作(?:约 .*秒|段 .*声明).*(?:支撑|离地.*厘米|穿入地面)|第 .* 段开门.*(?:IK 骨架链|可达范围))/.test(warning)),
        ...routeWarnings,
        ...doorContactWarnings,
        ...collisionWarnings,
        ...groundSupportWarnings,
        ...propSupportWarnings,
        ...contactWarnings,
        ...effectWarnings,
      ])];
      usePrevisStore.getState().setActionPrevis(anim.id, { ...latest, warnings });
    }
    return { ok: true, data: { animationId: anim.id, segmentIndex: index, updated: next[index], unchangedSegments: next.length - 1, warnings: [...result.warnings, ...contactWarnings, ...effectWarnings, ...doorContactWarnings, ...collisionWarnings, ...groundSupportWarnings, ...propSupportWarnings] } };
  } catch (e) {
    return err('REVISE_FAILED', e instanceof Error ? e.message : '动作段修改失败');
  }
}

async function setSceneProp(args: Record<string, unknown>): Promise<ToolResult> {
  const operation = reqStr(args, 'operation');
  const props = useWorldStore.getState().props;
  const id = optStr(args, 'id');
  const currentProp = id ? props.find((prop) => prop.id === id) : undefined;
  const addingSword = operation === 'add' && args['kind'] === 'sword';
  const touchesWeapon = addingSword || currentProp?.kind === 'sword';
  if (isPlanFieldLocked('environment') && !touchesWeapon) return err('FIELD_LOCKED', '场景物体已锁定；解锁后才能由 AI 修改');
  if (isPlanFieldLocked('weapons') && touchesWeapon) {
    return err('FIELD_LOCKED', '武器已锁定；解锁武器字段后才能由 AI 增删或调整武器');
  }
  if (isPlanFieldLocked('contacts') && id) {
    const plan = usePrevisStore.getState().byAnimationId[needAnim()?.id ?? '']?.scenePlan;
    if (plan?.contacts.some((contact) => contact.propId === id) && (operation === 'remove' || operation === 'update')) {
      return err('FIELD_LOCKED', '该道具绑定了已锁定的接触关系；解锁接触或改用其他道具');
    }
  }
  if (operation === 'remove') {
    if (!id) return err('BAD_ARGS', '移除道具需要 id');
    if (!props.some((prop) => prop.id === id)) return err('PROP_NOT_FOUND', `找不到道具 ${id}`);
    const activePlan = usePrevisStore.getState().byAnimationId[needAnim()?.id ?? '']?.scenePlan;
    if (activePlan?.actions.some((action) => action.targetPropId === id) && isPlanFieldLocked('actions')) {
      return err('FIELD_LOCKED', '该道具是已锁定动作段的目标；解锁动作后才能移除');
    }
    if (activePlan?.target.propId === id && isPlanFieldLocked('target')) {
      return err('FIELD_LOCKED', '该道具是已锁定的全局预演目标；解锁目标后才能移除');
    }
    useAnimationStore.getState().checkpoint();
    useWorldStore.getState().replaceProps(props.filter((prop) => prop.id !== id));
    syncScenePlanSnapshot();
    return { ok: true, data: { operation, id } };
  }
  if (operation !== 'add' && operation !== 'update') return err('BAD_ARGS', 'operation 必须是 add、update 或 remove');

  const kinds: StageProp['kind'][] = ['room', 'bed', 'chair', 'sofa', 'table', 'door', 'phone', 'sword', 'opponent'];
  const kindValue = operation === 'add' ? reqStr(args, 'kind') : props.find((prop) => prop.id === id)?.kind;
  if (!kindValue || !kinds.includes(kindValue as StageProp['kind'])) return err('BAD_ARGS', 'kind 必须是 room、bed、chair、sofa、table、door、phone、sword 或 opponent');
  const kind = kindValue as StageProp['kind'];
  const defaults: Record<StageProp['kind'], StageProp['size']> = {
    room: { width: 5, height: 3, length: 5 }, bed: { width: 1.3, height: 0.58, length: 2.1 },
    chair: { width: 0.52, height: 0.9, length: 0.52 }, table: { width: 1.1, height: 0.75, length: 0.7 },
    sofa: { width: 2.0, height: 0.9, length: 0.9 },
    door: { width: 0.9, height: 2.05, length: 0.08 }, phone: { width: 0.075, height: 0.018, length: 0.15 },
    sword: { width: 0.045, height: 0.045, length: 0.9 },
    opponent: { width: 0.62, height: 1.72, length: 0.42 },
  };
  const current = operation === 'update' ? props.find((prop) => prop.id === id) : undefined;
  if (operation === 'update' && !current) return err('PROP_NOT_FOUND', `找不到道具 ${id ?? ''}`);
  if (args['position'] !== undefined && !reqVec3(args, 'position')) return err('BAD_ARGS', 'position 必须是有限的三维坐标');
  const rawSize = args['size'];
  if (rawSize !== undefined && (typeof rawSize !== 'object' || rawSize === null || Array.isArray(rawSize)
    || Object.values(rawSize as Record<string, unknown>).some((value) => typeof value !== 'number' || !Number.isFinite(value) || value <= 0))) {
    return err('BAD_ARGS', 'size 的 width、height、length 必须是正数');
  }
  const sizePatch = (rawSize ?? {}) as Partial<StageProp['size']>;
  const attachTo = args['attachTo'];
  if (attachTo !== undefined && attachTo !== null && attachTo !== 'hand.R' && attachTo !== 'hand.L') return err('BAD_ARGS', 'attachTo 只支持 hand.R、hand.L 或 null');
  const position = args['position'] === undefined ? current?.position ?? defaultStagePropPosition(
    kind,
    kind === 'opponent' ? props.filter((prop) => prop.kind === 'opponent').length
      : kind === 'phone' ? props.filter((prop) => prop.kind === 'phone').length
        : kind === 'sofa' ? props.filter((prop) => prop.kind === 'sofa').length : 0,
  ) : reqVec3(args, 'position')!;
  const nextProp: StageProp = {
    id: current?.id ?? id ?? (kind === 'phone' ? `phone-${props.filter((prop) => prop.kind === 'phone').length + 1}` : `${kind}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`),
    kind,
    position,
    rotationY: optNum(args, 'rotationY', current?.rotationY ?? (kind === 'opponent' ? Math.atan2(-position[0], -position[2]) : 0)),
    size: { ...(current?.size ?? defaults[kind]), ...sizePatch },
    attachTo: kind === 'sword'
      ? (attachTo === undefined ? (current?.attachTo !== undefined ? current.attachTo : 'hand.R') : attachTo as 'hand.R' | 'hand.L' | null)
      : undefined,
    attachOffset: kind === 'sword' ? current?.attachOffset ?? [0, 0, 0] : undefined,
  };
  const targetMovementTemplates = new Set(['march', 'orient', 'sit', 'lie', 'sleep', 'reach', 'stand']);
  const changesTargetGeometry = Boolean(current && (
    JSON.stringify(current.position) !== JSON.stringify(nextProp.position)
    || current.rotationY !== nextProp.rotationY
    || JSON.stringify(current.size) !== JSON.stringify(nextProp.size)
  ));
  const lockedActionUsesTarget = current && changesTargetGeometry
    && usePrevisStore.getState().byAnimationId[needAnim()?.id ?? '']?.scenePlan?.actions.some((action) =>
      action.targetPropId === current.id && targetMovementTemplates.has(action.template));
  if (lockedActionUsesTarget && isPlanFieldLocked('actions')) {
    return err('FIELD_LOCKED', '该道具位置用于已锁定动作的走位；解锁动作后才能移动、旋转或改尺寸');
  }
  const limits = STAGE_PROP_SIZE_LIMITS[kind];
  for (const dimension of ['width', 'height', 'length'] as const) {
    const [minimum, maximum] = limits[dimension];
    const value = nextProp.size[dimension];
    if (value < minimum || value > maximum) {
      return err('BAD_ARGS', `${kind} 的 ${dimension} 必须在 ${minimum}–${maximum} 米之间；当前请求 ${value} 米，未修改场景`);
    }
  }
  const nextProps = current ? props.map((prop) => prop.id === current.id ? nextProp : prop) : [...props, nextProp];
  const overlap = findStagePropOverlaps(nextProps).find((item) => item.firstPropId === nextProp.id || item.secondPropId === nextProp.id);
  if (overlap) {
    return err('BAD_ARGS', `道具 ${overlap.firstPropId} 与 ${overlap.secondPropId} 的实体占位相交约 ${(overlap.overlapMeters * 100).toFixed(0)} 厘米；请调整位置、朝向或尺寸，场景未修改`);
  }
  const roomOverflows = findStagePropRoomOverflows(nextProps);
  const roomOverflow = kind === 'room'
    ? roomOverflows[0]
    : roomOverflows.find((item) => item.propId === nextProp.id);
  if (roomOverflow) {
    const axisName = roomOverflow.axis === 'width' ? '宽度' : roomOverflow.axis === 'length' ? '深度' : '净高';
    return err('BAD_ARGS', `道具 ${roomOverflow.propId} 超出房间${axisName}约 ${(roomOverflow.overflowMeters * 100).toFixed(0)} 厘米；请先调整房间或道具，场景未修改`);
  }
  const animation = needAnim();
  const animationId = animation?.id;
  const entry = animationId ? usePrevisStore.getState().byAnimationId[animationId] : undefined;
  const scene = useCharacterStore.getState().sceneObject;
  const snapshot = useSkeletonStore.getState().snapshot;
  let updatedTracks: BoneTrack[] | undefined;
  let trackWarnings: string[] = [];
  if (operation === 'update' && current && entry && animation && scene && snapshot
    && entry.segments.some((segment) => segment.targetPropId === current.id)) {
    const replanned = rebuildBoundTargetPositionTrack(animation, current.id, entry.segments, nextProps, scene, snapshot,
      entry.scenePlan?.target.propId === current.id ? entry.scenePlan.target.distanceMeters : undefined);
    if (replanned) {
      updatedTracks = replanned.tracks;
      trackWarnings = replanned.warnings;
      const doorBake = bakeDoorHandleContacts(scene, { ...animation, tracks: updatedTracks }, snapshot, nextProps, entry.segments,
        entry.scenePlan?.contacts ?? entry.contacts ?? []);
      updatedTracks = doorBake.animation.tracks;
      trackWarnings.push(...doorBake.warnings);
    }
  }
  if (updatedTracks && animation && JSON.stringify(updatedTracks) !== JSON.stringify(animation.tracks)) {
    useAnimationStore.getState().replaceActiveTracks(updatedTracks);
  } else {
    useAnimationStore.getState().checkpoint();
  }
  useWorldStore.getState().replaceProps(nextProps);
  syncScenePlanSnapshot();
  const regenerated = Boolean(updatedTracks && animation && JSON.stringify(updatedTracks) !== JSON.stringify(animation.tracks));
  const refreshWarnings = regenerated && scene && animation && entry
    ? [
      ...formatMotionCollisionWarnings(inspectMotionCollisions(scene, { ...animation, tracks: updatedTracks! }, nextProps, entry.segments, entry.scenePlan?.contacts ?? entry.contacts ?? [], snapshot!), scene),
      ...inspectGroundSupportWarnings(scene, { ...animation, tracks: updatedTracks! }, entry.segments, entry.scenePlan?.contacts ?? entry.contacts ?? [], nextProps.find((prop) => prop.kind === 'room')?.position[1] ?? 0),
      ...inspectPropSupportWarnings(scene, { ...animation, tracks: updatedTracks! }, entry.segments, entry.scenePlan?.contacts ?? entry.contacts ?? [], nextProps),
    ]
    : [];
  if (animationId && entry && (regenerated || trackWarnings.length > 0)) {
    const previousWarnings = entry.warnings ?? [];
    const preservedWarnings = previousWarnings.filter((warning) => !isMotionCollisionWarning(warning) && !/第 .* 段走位(?:已绕开|没有可从当前起点)|动作约 .* 声明.*(?:支撑|离地|穿入床面|穿入座面)/.test(warning));
    const newWarnings = regenerated
      ? ['场景道具尺寸/位置已变化，已重算绑定该道具的髋部走位轨道；肢体动作仍沿用原姿势。', ...trackWarnings, ...refreshWarnings]
      : [scene && snapshot
        ? '场景目标已变化，但没有可更新的髋部走位关键帧；既有动作轨道未重算，请重新生成并复核走位。'
        : '场景目标已变化，但缺少可用角色骨架，既有动作轨道未重算；请重新生成并复核走位。', ...trackWarnings];
    usePrevisStore.getState().setActionPrevis(animationId, { ...entry, warnings: [...new Set([...preservedWarnings, ...newWarnings])] });
  }
  return { ok: true, data: {
    operation,
    prop: useWorldStore.getState().props.find((prop) => prop.id === nextProp.id),
    ...(regenerated ? { replanned: true, warnings: [...trackWarnings, ...refreshWarnings] } : {}),
  } };
}

async function setCameraKeyframe(args: Record<string, unknown>): Promise<ToolResult> {
  const operation = reqStr(args, 'operation');
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '请先生成预演动画，再规划镜头');
  if (isPlanFieldLocked('camera')) return err('FIELD_LOCKED', '镜头已锁定；解锁后才能由 AI 修改');
  const time = reqNum(args, 'time');
  if (time === null || time < 0 || time > anim.duration) return err('BAD_ARGS', `time 必须在 0 到 ${anim.duration} 秒之间`);
  const camera = useCameraStore.getState();
  if (operation === 'remove') {
    if (!camera.keyframes.some((key) => Math.abs(key.time - time) < 1e-4)) return err('KEYFRAME_NOT_FOUND', `${time} 秒没有镜头关键帧`);
    useAnimationStore.getState().checkpoint();
    camera.deleteKeyframe(time);
    syncScenePlanSnapshot();
    return { ok: true, data: { operation, time, remaining: useCameraStore.getState().keyframes.length } };
  }
  if (operation !== 'upsert') return err('BAD_ARGS', 'operation 必须是 upsert 或 remove');
  const position = reqVec3(args, 'position');
  const target = reqVec3(args, 'target');
  const fov = reqNum(args, 'fov');
  if (!position || !target || fov === null || fov < 15 || fov > 100) return err('BAD_ARGS', '镜头关键帧需要有效 position、target 和 15–100 的 fov');
  useAnimationStore.getState().checkpoint();
  camera.upsertKeyframe({ time, position, target, fov }, anim.duration);
  camera.setEnabled(true);
  syncScenePlanSnapshot();
  return { ok: true, data: { operation, keyframe: useCameraStore.getState().keyframes.find((key) => Math.abs(key.time - time) < 1e-4) } };
}

async function setPrevisEffect(args: Record<string, unknown>): Promise<ToolResult> {
  const operation = reqStr(args, 'operation');
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '请先生成预演动画，再规划特效');
  if (isPlanFieldLocked('effects')) return err('FIELD_LOCKED', '特效已锁定；解锁后才能由 AI 修改');
  const id = optStr(args, 'id');
  const events = useEffectsStore.getState().events;
  const current = id ? events.find((event) => event.id === id && event.animationId === anim.id) : undefined;
  if ((operation === 'update' || operation === 'remove') && !current) return err('EFFECT_NOT_FOUND', '当前动画中找不到该特效事件');
  if (operation === 'remove') {
    useAnimationStore.getState().checkpoint();
    useEffectsStore.getState().remove(id!);
    syncScenePlanSnapshot();
    return { ok: true, data: { operation, id } };
  }
  if (operation !== 'add' && operation !== 'update') return err('BAD_ARGS', 'operation 必须是 add、update 或 remove');
  const kindValue = operation === 'add' ? reqStr(args, 'kind') : (args['kind'] ?? current?.kind);
  if (!['slash', 'impact', 'dust', 'spark', 'smoke', 'energy'].includes(String(kindValue))) return err('BAD_ARGS', 'kind 必须是 slash、impact、dust、spark、smoke 或 energy');
  const hasPath = Object.hasOwn(args, 'path');
  const rawPath = args['path'];
  const path = rawPath === null ? undefined : rawPath as PrevisEffectEvent['path'];
  if (hasPath && rawPath !== null && (!Array.isArray(rawPath) || rawPath.length < 2 || rawPath.length > 64
    || rawPath.some((point) => !Array.isArray(point) || point.length !== 3 || !point.every((value) => typeof value === 'number' && Number.isFinite(value) && Math.abs(value) <= 100)))) {
    return err('BAD_ARGS', 'path 必须是 2–64 个有限三维坐标点，坐标范围为 -100 到 100 米');
  }
  if (hasPath && path && kindValue !== 'slash') return err('BAD_ARGS', '只有 slash 挥砍拖尾支持 path 轨迹');
  const hasBladeSweep = Object.hasOwn(args, 'bladeSweep');
  const rawBladeSweep = args['bladeSweep'];
  const bladeSweep = rawBladeSweep === null ? undefined : rawBladeSweep as BladeSweepSample[];
  if (hasBladeSweep && rawBladeSweep !== null && (!Array.isArray(rawBladeSweep) || rawBladeSweep.length < 2 || rawBladeSweep.length > 64
    || rawBladeSweep.some((sample) => typeof sample !== 'object' || sample === null
      || !['base', 'tip'].every((key) => Array.isArray((sample as Record<string, unknown>)[key])
        && ((sample as Record<string, unknown>)[key] as unknown[]).length === 3
        && ((sample as Record<string, unknown>)[key] as unknown[]).every((value) => typeof value === 'number' && Number.isFinite(value) && Math.abs(value) <= 100))))) {
    return err('BAD_ARGS', 'bladeSweep 必须是 2–64 个 hilt-to-tip 样本，每个 base/tip 为范围 -100 到 100 米内的有限三维坐标');
  }
  if (hasBladeSweep && bladeSweep && kindValue !== 'slash') return err('BAD_ARGS', '只有 slash 挥砍拖尾支持 bladeSweep');
  const time = args['time'] === undefined ? current?.time : reqNum(args, 'time');
  const position = args['position'] === undefined ? current?.position : reqVec3(args, 'position');
  if (time === null || time === undefined || time < 0 || time > anim.duration) return err('BAD_ARGS', `time 必须在 0 到 ${anim.duration} 秒之间`);
  const scenePlan = usePrevisStore.getState().byAnimationId[anim.id]?.scenePlan;
  if (!scenePlan) return err('NO_PREVIS_PLAN', '当前动画缺少动作方案，无法把特效绑定到动作段');
  const requestedActionIndex = args['actionIndex'] === undefined ? undefined : reqNum(args, 'actionIndex');
  const actionIndex = requestedActionIndex === undefined
    ? actionIndexAtTime(scenePlan.actions, time)
    : requestedActionIndex;
  if (actionIndex === null || actionIndex === undefined || !Number.isInteger(actionIndex) || !scenePlan.actions[actionIndex]) {
    return err('BAD_ARGS', '特效必须关联一个有效动作段；请提供 actionIndex 或将时间放到动作段范围内');
  }
  const action = scenePlan.actions[actionIndex];
  if (time < action.t0 - 1e-3 || time > action.t1 + 1e-3) {
    return err('BAD_ARGS', `特效触发时间 ${time.toFixed(2)}s 不在动作段 ${actionIndex + 1} 的 ${action.t0}–${action.t1}s 范围内`);
  }
  if (!position) return err('BAD_ARGS', 'position 必须是有限的三维坐标');
  const duration = args['duration'] === undefined ? current?.duration : reqNum(args, 'duration');
  const scale = args['scale'] === undefined ? current?.scale : reqNum(args, 'scale');
  if ((duration !== undefined && (duration === null || duration <= 0 || duration > 10)) || (scale !== undefined && (scale === null || scale <= 0 || scale > 5))) return err('BAD_ARGS', 'duration 必须在 0–10 秒之间，scale 必须在 0–5 之间');
  const color = args['color'] === undefined ? current?.color : reqStr(args, 'color');
  if (color !== undefined && (color === null || !/^#[\da-f]{6}$/i.test(color))) return err('BAD_ARGS', 'color 必须是 #RRGGBB 格式');
  const store = useEffectsStore.getState();
  useAnimationStore.getState().checkpoint();
  let changedId = id;
  if (operation === 'add') {
    store.add(kindValue as PrevisEffectKind, time, anim.id, position, actionIndex, path, bladeSweep);
    const added = useEffectsStore.getState().events.at(-1)!;
    changedId = added.id;
    useEffectsStore.getState().update(added.id, {
      ...(duration !== undefined && duration !== null ? { duration } : {}),
      ...(scale !== undefined && scale !== null ? { scale } : {}),
      ...(color !== undefined && color !== null ? { color } : {}),
    });
  } else {
    store.update(id!, {
      kind: kindValue as PrevisEffectKind, time, position, actionIndex,
      ...(hasPath ? { path } : {}),
      ...(hasBladeSweep ? { bladeSweep } : {}),
      ...(duration !== undefined && duration !== null ? { duration } : {}),
      ...(scale !== undefined && scale !== null ? { scale } : {}),
      ...(color !== undefined && color !== null ? { color } : {}),
    });
  }
  syncScenePlanSnapshot();
  return { ok: true, data: { operation, event: useEffectsStore.getState().events.find((event) => event.id === changedId) } };
}

async function setPrevisTarget(args: Record<string, unknown>): Promise<ToolResult> {
  const animation = needAnim();
  if (!animation) return err('NO_ANIMATION', '请先生成预演动画，再修改预演目标');
  if (isPlanFieldLocked('target')) return err('FIELD_LOCKED', '预演目标/距离已锁定；解锁后才能由 AI 修改');
  const entry = usePrevisStore.getState().byAnimationId[animation.id];
  if (!entry?.scenePlan) return err('NO_PREVIS_PLAN', '当前动画没有可编辑的预演方案');

  const target = { ...entry.scenePlan.target };
  const previousPropId = target.propId;
  const previousDistance = target.distanceMeters;
  if (!Object.hasOwn(args, 'propId') && !Object.hasOwn(args, 'distanceMeters')) {
    return err('BAD_ARGS', '至少提供 propId 或 distanceMeters');
  }
  if (Object.hasOwn(args, 'propId')) {
    const propId = args['propId'];
    if (propId !== null && (typeof propId !== 'string' || !useWorldStore.getState().props.some((prop) => prop.id === propId))) {
      return err('BAD_ARGS', 'propId 必须是当前场景道具 ID 或 null');
    }
    if (typeof propId === 'string') target.propId = propId;
    else {
      delete target.propId;
      delete target.distanceMeters;
    }
  }
  if (Object.hasOwn(args, 'distanceMeters')) {
    const distanceMeters = args['distanceMeters'];
    if (distanceMeters !== null && (typeof distanceMeters !== 'number' || !Number.isFinite(distanceMeters) || distanceMeters < 0 || distanceMeters > 30)) {
      return err('BAD_ARGS', 'distanceMeters 必须是 0–30 米之间的有限数值或 null');
    }
    if (typeof distanceMeters === 'number') target.distanceMeters = distanceMeters;
    else delete target.distanceMeters;
  }
  const propIdChanged = target.propId !== previousPropId;
  const distanceChanged = target.distanceMeters !== previousDistance;
  const changed = propIdChanged || distanceChanged;
  if (!changed) return { ok: true, data: { target, unchanged: true, warnings: [] } };
  if (propIdChanged && target.propId !== previousPropId) {
    const contactBound = entry.scenePlan.contacts.some((contact) =>
      contact.propId === previousPropId
      && entry.segments.some((segment) => segment.targetPropId === previousPropId && (contact.phase === segment.template || contact.phase === segment.clause)));
    if (contactBound && isPlanFieldLocked('contacts')) return err('FIELD_LOCKED', '目标用于已锁定的接触关系；解锁接触后才能更换目标');
    const props = useWorldStore.getState().props;
    const targetIsSword = (propId?: string) => props.some((prop) => prop.id === propId && prop.kind === 'sword');
    if ((targetIsSword(previousPropId) || targetIsSword(target.propId)) && isPlanFieldLocked('weapons')) {
      return err('FIELD_LOCKED', '目标关联到已锁定武器；解锁武器后才能更换目标');
    }
  }
  if (target.distanceMeters !== undefined && !target.propId) {
    return err('BAD_ARGS', '设置目标距离时必须同时保留或指定 propId');
  }

  const props = useWorldStore.getState().props;
  const targetProp = target.propId ? props.find((prop) => prop.id === target.propId) : undefined;
  const movementTemplates = new Set(['march', 'orient', 'sit', 'lie', 'sleep', 'reach']);
  const segments = entry.segments.map((segment) => {
    const next = { ...segment };
    const followsPreviousTarget = Boolean(previousPropId && segment.targetPropId === previousPropId);
    const isUnboundInteraction = !segment.targetPropId && movementTemplates.has(segment.template);
    if (propIdChanged && typeof target.propId === 'string' && (followsPreviousTarget || isUnboundInteraction)) {
      next.targetPropId = target.propId;
    } else if (propIdChanged && !target.propId && followsPreviousTarget) {
      delete next.targetPropId;
    }
    return next;
  });
  const actionSegmentsChanged = JSON.stringify(segments) !== JSON.stringify(entry.segments);
  const targetAffectsMovement = Boolean(target.propId && segments.some((segment) =>
    movementTemplates.has(segment.template)
    && (!segment.targetPropId || segment.targetPropId === target.propId)));
  const rebuildsLockedActions = actionSegmentsChanged || (propIdChanged || distanceChanged) && targetAffectsMovement;
  if (rebuildsLockedActions && isPlanFieldLocked('actions')) {
    return err('FIELD_LOCKED', '该目标修改会改绑或重算已锁定的动作轨道；解锁动作后才能继续');
  }

  const scene = useCharacterStore.getState().sceneObject;
  const snapshot = useSkeletonStore.getState().snapshot;
  if (!scene || !snapshot) return err('NO_CHARACTER', '修改动作目标需要当前角色的骨架与场景');
  let tracks = animation.tracks;
  let trackWarnings: string[] = [];
  let doorContactWarnings: string[] = [];
  if (scene && snapshot && rebuildsLockedActions) {
    const targetFrame = targetProp
      ? targetProp.kind === 'bed'
        ? resolveBedInteractionFrame(targetProp, scene, snapshot, props, target.distanceMeters)
        : resolvePropInteractionFrame(targetProp, scene, snapshot, props, target.distanceMeters)
      : null;
    if (targetFrame?.pathObstructed && !targetFrame.approachPath) target.obstructed = true;
    else delete target.obstructed;
    const worldInteractions = Object.fromEntries([...new Set(segments.flatMap((segment) => segment.targetPropId ? [segment.targetPropId] : []))]
      .flatMap((id) => {
        const prop = props.find((item) => item.id === id);
        if (!prop) return [];
        const distance = id === target.propId ? target.distanceMeters : undefined;
        const frame = prop.kind === 'bed'
          ? resolveBedInteractionFrame(prop, scene, snapshot, props, distance)
          : resolvePropInteractionFrame(prop, scene, snapshot, props, distance);
        return frame ? [[id, frame] as const] : [];
      }));
    const segmentInteractions = resolveSequentialInteractionFrames(segments, scene, snapshot, props,
      target.propId ? { [target.propId]: target.distanceMeters } : undefined);
    const generated = generatePlannedTracks(buildBoneMap(snapshot), segments, animation.duration, 7, buildRestMap(snapshot), buildRestPositionMap(snapshot), targetFrame, worldInteractions, segmentInteractions,
      props.find((prop) => prop.kind === 'room')?.position[1] ?? 0,
      estimateGroundHipLocalOffset(scene, snapshot, props.find((prop) => prop.kind === 'room')?.position[1] ?? 0));
    tracks = correctGroundedLegTracks(scene, { ...animation, tracks: generated.tracks }, buildBoneMap(snapshot), segments,
      entry.scenePlan.contacts, props.find((prop) => prop.kind === 'room')?.position[1] ?? 0);
    trackWarnings = generated.warnings;
    const baked = bakeDoorHandleContacts(scene, { ...animation, tracks }, snapshot, props, segments, entry.scenePlan.contacts);
    tracks = baked.animation.tracks;
    doorContactWarnings = baked.warnings;
  }
  if (tracks !== animation.tracks) useAnimationStore.getState().replaceActiveTracks(tracks);
  const routeWarnings = trackWarnings.filter((warning) => /段走位(?:已绕开|没有可从当前起点)/.test(warning));
  const warnings = [...new Set([...(entry.warnings ?? []).filter((warning) => !/段走位(?:已绕开|没有可从当前起点)/.test(warning) && !/第 .* 段开门.*(?:IK 骨架链|可达范围)/.test(warning)), ...routeWarnings, ...doorContactWarnings])];
  usePrevisStore.getState().setActionPrevis(animation.id, {
    ...entry,
    warnings,
    segments,
    scenePlan: { ...entry.scenePlan, target, actions: segments },
  });
  return { ok: true, data: { target, warnings: doorContactWarnings } };
}

async function setPrevisEvent(args: Record<string, unknown>): Promise<ToolResult> {
  const animation = needAnim();
  if (!animation) return err('NO_ANIMATION', '请先生成预演动画，再编辑事件');
  if (isPlanFieldLocked('events')) return err('FIELD_LOCKED', '事件已锁定；解锁后才能由 AI 修改');
  const entry = usePrevisStore.getState().byAnimationId[animation.id];
  if (!entry?.scenePlan) return err('NO_PREVIS_PLAN', '当前动画没有可编辑的预演方案');
  const operation = reqStr(args, 'operation');
  if (operation !== 'add' && operation !== 'update' && operation !== 'remove') return err('BAD_ARGS', 'operation 必须是 add、update 或 remove');
  const events = structuredClone(entry.scenePlan.events);

  if (operation === 'add') {
    const actionIndex = reqNum(args, 'actionIndex');
    if (actionIndex === null || !Number.isInteger(actionIndex) || !entry.scenePlan.actions[actionIndex]) return err('BAD_ARGS', 'actionIndex 必须指向当前存在的动作段');
    const action = entry.scenePlan.actions[actionIndex];
    const time = args['time'] === undefined ? action.t0 : reqNum(args, 'time');
    const label = reqStr(args, 'label')?.trim();
    if (time === null || time === undefined || time < action.t0 || time > action.t1) return err('BAD_ARGS', `time 必须位于动作段 ${actionIndex} 的 ${action.t0}–${action.t1} 秒内`);
    if (!label || label.length > 120) return err('BAD_ARGS', 'label 不能为空且不能超过 120 字');
    events.push({ actionIndex, time, label });
  } else {
    const eventIndex = reqNum(args, 'eventIndex');
    if (eventIndex === null || !Number.isInteger(eventIndex) || eventIndex < 0 || eventIndex >= events.length) return err('BAD_ARGS', 'eventIndex 必须指向当前存在的事件');
    if (operation === 'remove') events.splice(eventIndex, 1);
    else {
      const current = events[eventIndex];
      const actionIndex = args['actionIndex'] === undefined ? current.actionIndex : reqNum(args, 'actionIndex');
      if (actionIndex === null || actionIndex === undefined || !Number.isInteger(actionIndex) || !entry.scenePlan.actions[actionIndex]) return err('BAD_ARGS', 'actionIndex 必须指向当前存在的动作段');
      const action = entry.scenePlan.actions[actionIndex];
      const time = args['time'] === undefined ? current.time : reqNum(args, 'time');
      const label = args['label'] === undefined ? current.label : reqStr(args, 'label')?.trim();
      if (time === null || time === undefined || time < action.t0 || time > action.t1) return err('BAD_ARGS', `time 必须位于动作段 ${actionIndex} 的 ${action.t0}–${action.t1} 秒内`);
      if (!label || label.length > 120) return err('BAD_ARGS', 'label 不能为空且不能超过 120 字');
      events[eventIndex] = { actionIndex, time, label };
    }
  }

  events.sort((a, b) => a.time - b.time);
  useAnimationStore.getState().checkpoint();
  usePrevisStore.getState().setActionPrevis(animation.id, {
    ...entry,
    scenePlan: { ...entry.scenePlan, events },
  });
  return { ok: true, data: { operation, events } };
}

async function setFaceKeyframe(args: Record<string, unknown>): Promise<ToolResult> {
  const operation = reqStr(args, 'operation');
  if (operation !== 'upsert' && operation !== 'remove') return err('BAD_ARGS', 'operation 必须是 upsert 或 remove');
  const animation = needAnim();
  if (!animation) return err('NO_ANIMATION', '请先创建或生成动画，再编辑表情关键帧');
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const meshPath = reqStr(args, 'meshPath');
  const targetName = reqStr(args, 'targetName');
  const time = reqNum(args, 'time');
  if (!meshPath || !targetName || time === null || time < 0 || time > animation.duration) {
    return err('BAD_ARGS', `需要有效 meshPath、targetName，time 须在 0 到 ${animation.duration} 秒之间`);
  }
  const target = listMorphTargets(scene).find((item) => item.meshPath === meshPath && item.name === targetName);
  if (!target) return err('MORPH_NOT_FOUND', `当前角色不存在 ${meshPath} 的表情目标 ${targetName}`);
  if (operation === 'remove') {
    if (!useAnimationStore.getState().deleteFaceKey(meshPath, targetName, time)) return err('KEYFRAME_NOT_FOUND', `${targetName} 在 ${time} 秒没有表情关键帧`);
    return { ok: true, data: { operation, meshPath, targetName, time } };
  }
  const value = reqNum(args, 'value');
  if (value === null || value < 0 || value > 1) return err('BAD_ARGS', '表情权重 value 必须在 0 到 1 之间');
  useAnimationStore.getState().upsertFaceKey(meshPath, targetName, time, value);
  return { ok: true, data: { operation, meshPath, targetName, time, value } };
}

async function applyIk(args: Record<string, unknown>): Promise<ToolResult> {
  const chain = reqStr(args, 'chain');
  if (chain !== 'arm.L' && chain !== 'arm.R' && chain !== 'leg.L' && chain !== 'leg.R') {
    return err('BAD_ARGS', 'apply_ik 的 chain 须为 arm.L/arm.R/leg.L/leg.R');
  }
  const id = chain as IKChainId;
  const st = useIKStore.getState();
  const c = st.chains[id];
  if (!c) return err('CHAIN_MISSING', `${chain} 未检测到（检查语义映射）`);
  const wantEnable = typeof args['enable'] === 'boolean' ? (args['enable'] as boolean) : !c.enabled;
  if (wantEnable !== c.enabled) st.toggleChain(id);
  const target = optVec3(args, 'target');
  if (target) st.setTarget(id, target);
  const delta = optVec3(args, 'targetDelta');
  if (delta) {
    const t = st.chains[id]?.target ?? c.target;
    st.setTarget(id, [t[0] + delta[0], t[1] + delta[1], t[2] + delta[2]]);
  }
  const pole = optVec3(args, 'polePoint');
  if (pole) st.setPolePoint(id, pole);
  const cur = useIKStore.getState().chains[id]!;
  // 同步求解（自检）：不等下一帧，立即把骨骼拉到目标，避免后续 keyframe 抓到旧姿势导致闪烁
  let solve: { reached: boolean; hingeDeg: number; clamped: boolean } | null = null;
  if (cur.enabled) {
    const scene = useCharacterStore.getState().sceneObject;
    if (scene) {
      try {
        const solved = solvePinsLive(scene, [{ def: cur.def, target: [...cur.target], polePoint: [...cur.polePoint] }]);
        const s = solved[0];
        if (s) {
          solve = { reached: s.reached, hingeDeg: s.hingeDeg, clamped: s.clamped };
          st.setLastSolve(id, { reached: s.reached, hingeDeg: s.hingeDeg, clamped: s.clamped });
        }
      } catch (e) {
        return err('IK_FAILED', e instanceof Error ? e.message : 'IK 求解失败');
      }
    }
  }
  return {
    ok: true,
    data: {
      chain,
      enabled: cur.enabled,
      target: cur.target,
      reached: solve?.reached ?? null,
      hingeDeg: solve ? Math.round(solve.hingeDeg * 10) / 10 : null,
      clamped: solve?.clamped ?? false,
    },
  };
}

async function applyInbetween(args: Record<string, unknown>): Promise<ToolResult> {
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动动画');
  const density = Math.min(Math.max(optNum(args, 'density', 12), 2), 120);
  const ease = optStr(args, 'ease');
  if (ease !== undefined && !['linear', 'easeIn', 'easeOut', 'easeInOut', 'easeOutIn'].includes(ease)) {
    return err('BAD_ARGS', 'ease 非法');
  }
  const r = await mathInbetween.runInbetween({
    animation: anim,
    minTime: 0,
    maxTime: anim.duration,
    density,
    ease: (ease ?? 'linear') as 'linear',
  });
  const st = useAnimationStore.getState();
  st.replaceAll([r.animation, ...st.animations.filter((a) => a.id !== anim.id)], anim.id);
  return { ok: true, data: { addedKeys: r.meta.addedKeys } };
}

async function checkPhysics(): Promise<ToolResult> {
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动动画');
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return err('NO_CHARACTER', '无骨骼快照');
  const bySem = new Map(Object.values(snap.nodes).map((n) => [n.semantic, n.name]));
  const hips = bySem.get('hips');
  if (!hips) return err('NO_HIPS', '未找到 hips 骨骼');
  const jointLimits = Object.values(snap.nodes).flatMap((node) => node.semantic && JOINT_LIMIT_DEGREES[node.semantic] !== undefined
    ? [{ semantic: node.semantic, boneName: node.name, restQuaternion: node.restLocal.quaternion, maxDegrees: JOINT_LIMIT_DEGREES[node.semantic]! }]
    : []);
  const { samples, warnings } = collectTrajectory(
    scene,
    anim,
    {
      hips, footL: bySem.get('foot.L') ?? null, footR: bySem.get('foot.R') ?? null,
      massBones: Object.fromEntries([...bySem].filter(([semantic, name]) => semantic && name)),
      jointLimits,
    },
    30,
  );
  const issues = analyzeTrajectory(samples, jointLimits);
  const previs = usePrevisStore.getState().byAnimationId[anim.id];
  const props = useWorldStore.getState().props;
  const segments = previs?.segments ?? [];
  const contacts = previs?.scenePlan?.contacts ?? previs?.contacts ?? [];
  const collisionFindings = inspectMotionCollisions(scene, anim, props, segments, contacts, snap);
  const collisionWarnings = formatMotionCollisionWarnings(collisionFindings, scene);
  const supportWarnings = [
    ...inspectGroundSupportWarnings(scene, anim, segments, contacts, props.find((prop) => prop.kind === 'room')?.position[1] ?? 0),
    ...inspectPropSupportWarnings(scene, anim, segments, contacts, props),
  ];
  return { ok: true, data: { issues, warnings, collisionFindings, collisionWarnings, supportWarnings } };
}

async function repairJointLimit(args: Record<string, unknown>): Promise<ToolResult> {
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动动画');
  const boneName = optStr(args, 'boneName');
  const time = optNum(args, 'time', Number.NaN);
  if (!boneName || !Number.isFinite(time) || time < 0 || time > anim.duration) {
    return err('BAD_ARGS', '需提供有效的 boneName 与动画范围内 time');
  }
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return err('NO_CHARACTER', '无骨骼快照');
  const node = Object.values(snap.nodes).find((item) => item.name === boneName);
  const threshold = node?.semantic ? JOINT_LIMIT_DEGREES[node.semantic] : undefined;
  if (!node || threshold === undefined) return err('NO_JOINT_LIMIT', `${boneName} 没有可用的关节预警阈值`);
  const limit = { semantic: node.semantic!, boneName, restQuaternion: node.restLocal.quaternion, maxDegrees: threshold };
  const bySem = new Map(Object.values(snap.nodes).map((item) => [item.semantic, item.name]));
  const hips = bySem.get('hips');
  if (!hips) return err('NO_HIPS', '未找到 hips 骨骼');
  const { samples, warnings } = collectTrajectory(scene, anim, {
    hips,
    footL: bySem.get('foot.L') ?? null,
    footR: bySem.get('foot.R') ?? null,
    massBones: Object.fromEntries([...bySem].filter(([semantic, name]) => semantic && name)),
    jointLimits: [limit],
  }, 30);
  const issue = analyzeTrajectory(samples, [limit]).find((item) =>
    item.kind === 'jointLimit' && item.boneName === boneName && time >= item.t0 - 1 / 30 && time <= item.t1 + 1 / 30,
  );
  if (!issue) return err('ISSUE_NOT_FOUND', `${boneName} 在 ${time.toFixed(2)}s 附近没有关节限幅问题`);
  const entries = buildJointLimitEntries(anim, issue, limit);
  if (entries.length === 0) return err('NO_REPAIR_KEYS', `${boneName} 没有可修复的旋转关键帧`);
  useAnimationStore.getState().bakePoseKeys(entries, []);
  return { ok: true, data: { boneName, interval: [issue.t0, issue.t1], maxDegrees: threshold, keysWritten: entries.length, warnings, undoable: true } };
}

async function repairPhysics(args: Record<string, unknown>): Promise<ToolResult> {
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const anim = needAnim();
  if (!anim) return err('NO_ANIMATION', '无活动动画');
  const kind = optStr(args, 'kind');
  const time = optNum(args, 'time', Number.NaN);
  const footArg = optStr(args, 'foot');
  if (!['penetration', 'footSlide', 'accelSpike', 'balance'].includes(kind ?? '') || !Number.isFinite(time) || time < 0 || time > anim.duration) {
    return err('BAD_ARGS', 'kind 须为 penetration、footSlide、accelSpike 或 balance，并提供动画范围内 time');
  }
  if (footArg !== undefined && footArg !== 'L' && footArg !== 'R') return err('BAD_ARGS', 'foot 只能是 L 或 R');
  const snap = useSkeletonStore.getState().snapshot;
  if (!snap) return err('NO_CHARACTER', '无骨骼快照');
  const bySem = new Map(Object.values(snap.nodes).map((node) => [node.semantic, node.name]));
  const hips = bySem.get('hips');
  if (!hips) return err('NO_HIPS', '未找到 hips 骨骼');
  const names = {
    hips,
    footL: bySem.get('foot.L') ?? null,
    footR: bySem.get('foot.R') ?? null,
    massBones: Object.fromEntries([...bySem].filter(([semantic, name]) => semantic && name)),
  };
  const { samples, warnings } = collectTrajectory(scene, anim, names, 30);
  const issues = analyzeTrajectory(samples).filter((issue) => issue.kind === kind && time >= issue.t0 - 1 / 30 && time <= issue.t1 + 1 / 30);
  const candidates = footArg ? issues.filter((issue) => issue.foot === footArg) : issues;
  if (['penetration', 'footSlide'].includes(kind ?? '') && candidates.length > 1) return err('AMBIGUOUS_ISSUE', '该时刻有多个同类脚部问题，请提供 foot: L 或 R');
  // Impact and balance checks may report adjacent intervals; use the nearest matching interval.
  const issue = kind === 'accelSpike' || kind === 'balance'
    ? candidates.reduce<(typeof candidates)[number] | undefined>((nearest, item) => !nearest || Math.abs(item.t0 - time) < Math.abs(nearest.t0 - time) ? item : nearest, undefined)
    : candidates[0];
  if (!issue) return err('ISSUE_NOT_FOUND', `${kind} 在 ${time.toFixed(2)}s 附近没有匹配的问题；脚部问题请检查 foot 参数`);

  let rot: ReturnType<typeof buildJointLimitEntries> = [];
  let pos: ReturnType<typeof buildHipsLiftEntries> = [];
  let repairWarnings = [...warnings];
  if (issue.kind === 'penetration') {
    pos = buildHipsLiftEntries(samples, [issue], hips);
  } else if (issue.kind === 'accelSpike') {
    pos = buildSmoothedHipsEntries(samples, [issue], hips);
  } else if (issue.kind === 'footSlide' && issue.foot) {
    const chainId = (issue.foot === 'L' ? 'leg.L' : 'leg.R') as IKChainId;
    const chain = useIKStore.getState().chains[chainId];
    if (!chain) return err('IK_CHAIN_MISSING', `${chainId} IK 链未映射，无法执行脚锁`);
    const result = buildFootLockEntries(scene, anim, issue, chain.def, [...chain.polePoint]);
    rot = result.entries;
    repairWarnings = [...repairWarnings, ...result.warnings];
  } else if (issue.kind === 'balance') {
    const chains = useIKStore.getState().chains;
    const result = buildBalanceCorrectionEntries(scene, anim, samples, issue, hips, {
      ...(chains['leg.L'] ? { L: { def: chains['leg.L'].def, polePoint: [...chains['leg.L'].polePoint] as [number, number, number] } } : {}),
      ...(chains['leg.R'] ? { R: { def: chains['leg.R'].def, polePoint: [...chains['leg.R'].polePoint] as [number, number, number] } } : {}),
    });
    pos = result.pos;
    rot = result.rot;
    repairWarnings = [...repairWarnings, ...result.warnings];
  }
  if (rot.length === 0 && pos.length === 0) {
    const reason = repairWarnings.length > 0 ? repairWarnings.join('；') : '该问题未生成修复关键帧；请重新检查轨迹与骨架映射';
    return err('NO_REPAIR_KEYS', reason);
  }
  useAnimationStore.getState().bakePoseKeys(rot, pos);
  const updatedAnimation = useAnimationStore.getState().active();
  const remainingIssues = updatedAnimation
    ? analyzeTrajectory(collectTrajectory(scene, updatedAnimation, names, 30).samples)
      .filter((item) => item.kind === issue.kind && item.t0 <= issue.t1 + 0.1 && item.t1 >= issue.t0 - 0.1)
    : [];
  repairWarnings.push(...remainingIssues.map((item) => `复检仍发现：${item.message}`));
  return { ok: true, data: {
    kind: issue.kind, foot: issue.foot, interval: [issue.t0, issue.t1],
    rotationKeysWritten: rot.length, positionKeysWritten: pos.length,
    remainingIssues, warnings: repairWarnings, undoable: true,
  } };
}

async function exportAnimation(args: Record<string, unknown>): Promise<ToolResult> {
  const scene = needScene();
  if (!(scene instanceof THREE.Group)) return scene as ToolResult;
  const meta = useCharacterStore.getState().meta;
  if (!meta) return err('NO_CHARACTER', '无角色元信息');
  const anims = useAnimationStore.getState().animations;
  const onlyId = optStr(args, 'animationId');
  const list = onlyId ? anims.filter((a) => a.id === onlyId) : anims;
  if (list.length === 0) return err('NO_ANIMATION', '无可导出动画');
  try {
    const { exportGltf } = await import('../export/exportGltf');
    const r = await exportGltf(scene, list, meta.fileName);
    return { ok: true, data: { fileName: r.fileName, clipCount: r.clipCount, warnings: r.warnings } };
  } catch (e) {
    return err('EXPORT_FAILED', e instanceof Error ? e.message : '导出失败');
  }
}

/* ---------- 分发 + 幂等 ---------- */

const seen = new Map<string, ToolResult>();

const HANDLERS: Record<ToolName, (args: Record<string, unknown>) => Promise<ToolResult>> = {
  load_character: () => Promise.resolve(err('NEEDS_USER_FILE', 'load_character 需用户拖入 GLB 文件，Agent 无法代传文件')),
  inspect_skeleton: inspectSkeleton,
  select_bone: selectBone,
  modify_bone: modifyBone,
  create_keyframe: createKeyframe,
  delete_keyframe: deleteKeyframe,
  create_animation: createAnimation,
  generate_motion: generateMotion,
  revise_action_segment: reviseActionSegment,
  set_scene_prop: setSceneProp,
  set_previs_target: setPrevisTarget,
  set_previs_event: setPrevisEvent,
  set_camera_keyframe: setCameraKeyframe,
  set_previs_effect: setPrevisEffect,
  set_face_keyframe: setFaceKeyframe,
  retarget_motion: () =>
    Promise.resolve(err('RESERVED', 'retarget 已内建于 generate_motion，独立 retarget 后续版本提供')),
  apply_ik: applyIk,
  apply_inbetween: applyInbetween,
  check_physics: checkPhysics,
  repair_joint_limit: repairJointLimit,
  repair_physics: repairPhysics,
  export_animation: exportAnimation,
};

export function parseAction(raw: unknown): { action?: AgentAction; error?: string } {
  if (typeof raw !== 'object' || raw === null) return { error: 'action 须为对象' };
  const r = raw as Record<string, unknown>;
  if (!isToolName(r['tool'])) return { error: `未知 tool: ${String(r['tool'])}` };
  if (typeof r['args'] !== 'object' || r['args'] === null) return { error: 'args 须为对象' };
  if (typeof r['idempotencyKey'] !== 'string' || (r['idempotencyKey'] as string).length === 0) {
    return { error: 'idempotencyKey 须为非空字符串' };
  }
  return { action: { tool: r['tool'], args: r['args'] as Record<string, unknown>, idempotencyKey: r['idempotencyKey'] as string } };
}

export async function executeAction(raw: unknown): Promise<ToolResult> {
  const { action, error } = parseAction(raw);
  if (!action) return err('BAD_ACTION', error ?? '非法 action');
  if (seen.has(action.idempotencyKey)) {
    const cached = seen.get(action.idempotencyKey)!;
    return { ...cached, data: { ...((cached.data as Record<string, unknown> | undefined) ?? {}), idempotentReplay: true } };
  }
  try {
    const result = await HANDLERS[action.tool](action.args);
    seen.set(action.idempotencyKey, result);
    return result;
  } catch (e) {
    const r = err('TOOL_CRASH', e instanceof Error ? e.message : String(e));
    seen.set(action.idempotencyKey, r);
    return r;
  }
}

export async function executeActions(actions: AgentAction[]): Promise<ToolResult[]> {
  const out: ToolResult[] = [];
  for (const a of actions) out.push(await executeAction(a));
  return out;
}

export function clearIdempotencyCache() {
  seen.clear();
}
