import { create } from 'zustand';
import { DEFAULT_CAMERA_POSE, sanitizeCameraKeyframe, type CameraKeyframe } from '../core/camera/track';

interface CameraState {
  activeAnimationId: string | null;
  activationRevision: number;
  enabled: boolean;
  keyframes: CameraKeyframe[];
  autoGenerated: boolean;
  activateAnimation: (animationId: string | null, track?: { enabled?: boolean; keyframes?: CameraKeyframe[]; autoGenerated?: boolean }, duration?: number) => void;
  setEnabled: (enabled: boolean) => void;
  upsertKeyframe: (keyframe: CameraKeyframe, duration: number) => void;
  deleteKeyframe: (time: number) => void;
  setKeyframes: (keyframes: CameraKeyframe[], duration: number, autoGenerated?: boolean) => void;
  createDefaultPath: (duration: number) => void;
  clear: () => void;
}

const EPS = 1e-4;

export const useCameraStore = create<CameraState>((set) => ({
  activeAnimationId: null,
  activationRevision: 0,
  enabled: false,
  keyframes: [],
  autoGenerated: false,
  activateAnimation: (animationId, track, duration = 4) => set((state) => ({
    activeAnimationId: animationId,
    activationRevision: state.activationRevision + 1,
    enabled: track?.enabled ?? Boolean(track?.keyframes?.length),
    keyframes: (track?.keyframes ?? []).map((key) => sanitizeCameraKeyframe(key, duration)).sort((a, b) => a.time - b.time),
    autoGenerated: track?.autoGenerated ?? false,
  })),
  setEnabled: (enabled) => set({ enabled }),
  upsertKeyframe: (keyframe, duration) => set((state) => {
    const clean = sanitizeCameraKeyframe(keyframe, duration);
    const keys = state.keyframes.filter((key) => Math.abs(key.time - clean.time) >= EPS);
    return { keyframes: [...keys, clean].sort((a, b) => a.time - b.time), autoGenerated: false };
  }),
  deleteKeyframe: (time) => set((state) => ({ keyframes: state.keyframes.filter((key) => Math.abs(key.time - time) >= EPS), autoGenerated: false })),
  setKeyframes: (keyframes, duration, autoGenerated = false) => set({ keyframes: keyframes.map((key) => sanitizeCameraKeyframe(key, duration)).sort((a, b) => a.time - b.time), autoGenerated }),
  createDefaultPath: (duration) => set({
    enabled: true,
    autoGenerated: false,
    keyframes: [
      { time: 0, ...DEFAULT_CAMERA_POSE },
      { time: duration, position: [1.65, 1.55, 2.45], target: [0, 1.05, 0.25], fov: 52 },
    ],
  }),
  clear: () => set({ enabled: false, keyframes: [], autoGenerated: false }),
}));
