import { create } from 'zustand';
import type { AnimationData } from '../core/animation/types';
import type { ActionPrevisData } from './previsStore';
import type { StageProp } from '../core/previs/world';
import type { CameraKeyframe } from '../core/camera/track';
import type { PrevisEffectEvent } from '../core/previs/effects';

const LIMIT = 50;

function clone(anims: AnimationData[]): AnimationData[] {
  return structuredClone(anims);
}

export interface EditorHistoryContext {
  previs: Record<string, ActionPrevisData>;
  props: StageProp[];
  camera: { activeAnimationId: string | null; enabled: boolean; keyframes: CameraKeyframe[]; autoGenerated: boolean };
  effects: PrevisEffectEvent[];
}

interface HistoryState {
  past: AnimationData[][];
  future: AnimationData[][];
  pastContext: EditorHistoryContext[];
  futureContext: EditorHistoryContext[];
  push: (snapshot: AnimationData[], context: EditorHistoryContext) => void;
  undo: (current: AnimationData[], currentContext: EditorHistoryContext) => { animations: AnimationData[]; context: EditorHistoryContext } | null;
  redo: (current: AnimationData[], currentContext: EditorHistoryContext) => { animations: AnimationData[]; context: EditorHistoryContext } | null;
  clear: () => void;
  canUndo: () => boolean;
  canRedo: () => boolean;
}

export const useHistoryStore = create<HistoryState>((set, get) => ({
  past: [],
  future: [],
  pastContext: [],
  futureContext: [],
  push: (snapshot, context) => set((s) => ({
    past: [...s.past.slice(-LIMIT + 1), clone(snapshot)],
    pastContext: [...s.pastContext.slice(-LIMIT + 1), structuredClone(context)],
    future: [],
    futureContext: [],
  })),
  undo: (current, currentPrevis) => {
    const { past, future, pastContext, futureContext } = get();
    if (past.length === 0) return null;
    const prev = past[past.length - 1];
    const prevContext = pastContext[pastContext.length - 1];
    set({
      past: past.slice(0, -1),
      pastContext: pastContext.slice(0, -1),
      future: [clone(current), ...future].slice(0, LIMIT),
      futureContext: [structuredClone(currentPrevis), ...futureContext].slice(0, LIMIT),
    });
    return { animations: clone(prev), context: structuredClone(prevContext ?? { previs: {}, props: [], camera: { activeAnimationId: null, enabled: false, keyframes: [], autoGenerated: false }, effects: [] }) };
  },
  redo: (current, currentContext) => {
    const { past, future, pastContext, futureContext } = get();
    if (future.length === 0) return null;
    const [next, ...rest] = future;
    const [nextContext, ...restContext] = futureContext;
    set({
      past: [...past, clone(current)].slice(-LIMIT),
      pastContext: [...pastContext, structuredClone(currentContext)].slice(-LIMIT),
      future: rest,
      futureContext: restContext,
    });
    return { animations: clone(next), context: structuredClone(nextContext ?? { previs: {}, props: [], camera: { activeAnimationId: null, enabled: false, keyframes: [], autoGenerated: false }, effects: [] }) };
  },
  clear: () => set({ past: [], future: [], pastContext: [], futureContext: [] }),
  canUndo: () => get().past.length > 0,
  canRedo: () => get().future.length > 0,
}));
