import { create } from 'zustand';
import type { ScenePlan } from '../core/previs/scenePlan';
import type { ContactConstraint, StageProp } from '../core/previs/world';
import type { CameraKeyframe } from '../core/camera/track';
import { reconcileEffectsToActions, type PrevisEffectEvent } from '../core/previs/effects';
import { reconcileContactsToActions } from '../core/previs/contacts';
import { mapActionStageIndices, rebindActionTime } from '../core/previs/actionMapping';
import { useEffectsStore } from './effectsStore';

export interface ActionPrevisData {
  prompt: string;
  segments: Array<{ t0: number; t1: number; template: string; clause: string; intensity?: number; speed?: number; targetPropId?: string }>;
  contacts?: ContactConstraint[];
  warnings?: string[];
  scenePlan?: ScenePlan;
}

interface PrevisState {
  byAnimationId: Record<string, ActionPrevisData>;
  setActionPrevis: (animationId: string, data: ActionPrevisData) => void;
  updateSegments: (animationId: string, segments: ActionPrevisData['segments']) => void;
  updateStoryboardPrompts: (animationId: string, shots: NonNullable<ScenePlan['storyboard']>['shots']) => void;
  togglePlanLock: (animationId: string, field: string) => void;
  syncEditorContext: (props: StageProp[], effects: PrevisEffectEvent[], cameraKeyframes: CameraKeyframe[], durations: Record<string, number>, activeAnimationId?: string | null, cameraEnabled?: boolean, cameraAutoGenerated?: boolean) => void;
  replaceAll: (data: Record<string, ActionPrevisData>) => void;
  clear: () => void;
}

export const usePrevisStore = create<PrevisState>((set, get) => ({
  byAnimationId: {},
  setActionPrevis: (animationId, data) => set((state) => ({ byAnimationId: { ...state.byAnimationId, [animationId]: structuredClone(data) } })),
  updateSegments: (animationId, segments) => {
    const current = get().byAnimationId[animationId];
    if (!current) return;
    const contacts = reconcileContactsToActions(current.segments, segments,
      current.scenePlan?.contacts ?? current.contacts ?? []);
    const actionMapping = mapActionStageIndices(current.segments, segments);
    const currentEffects = useEffectsStore.getState().events;
    const ownedEffects = currentEffects.filter((event) => event.animationId === animationId);
    const reboundOwnedEffects = reconcileEffectsToActions(ownedEffects, current.segments, segments);
    const reboundById = new Map(reboundOwnedEffects.map((event) => [event.id, event]));
    const reboundEffects = currentEffects.flatMap((event) => {
      if (event.animationId !== animationId) return [event];
      const rebound = reboundById.get(event.id);
      return rebound ? [rebound] : [];
    });
    if (reboundEffects.length !== currentEffects.length
      || reboundEffects.some((event, index) => event !== currentEffects[index])) {
      useEffectsStore.getState().replace(reboundEffects);
    }
    set((state) => {
      const latest = state.byAnimationId[animationId];
      if (!latest) return state;
      const scenePlan = latest.scenePlan ? {
        ...latest.scenePlan,
        actions: structuredClone(segments),
        contacts: structuredClone(contacts),
        effects: structuredClone(reboundEffects.filter((event) => !event.animationId || event.animationId === animationId)),
        events: latest.scenePlan.events.flatMap((event) => {
          const previous = latest.segments[event.actionIndex];
          if (!previous) return [event];
          const nextIndex = actionMapping[event.actionIndex];
          if (nextIndex === null || nextIndex === undefined) return [];
          const updated = segments[nextIndex];
          if (!updated || updated.template !== previous.template) return [];
          const followsActionStart = Math.abs(event.time - previous.t0) < 1e-3 && event.label === previous.clause;
          return [{
            ...event,
            actionIndex: nextIndex,
            time: rebindActionTime(event.time, previous, updated),
            ...(followsActionStart ? { label: updated.clause } : {}),
          }];
        }),
      } : undefined;
      return { byAnimationId: { ...state.byAnimationId, [animationId]: {
        ...latest, segments: structuredClone(segments), contacts: structuredClone(contacts), scenePlan,
      } } };
    });
  },
  updateStoryboardPrompts: (animationId, shots) => set((state) => {
    const current = state.byAnimationId[animationId];
    if (!current?.scenePlan || current.scenePlan.lockedFields.includes('storyboard')) return state;
    return { byAnimationId: { ...state.byAnimationId, [animationId]: { ...current, scenePlan: { ...current.scenePlan, storyboard: { shots: structuredClone(shots) } } } } };
  }),
  togglePlanLock: (animationId, field) => set((state) => {
    const current = state.byAnimationId[animationId];
    if (!current?.scenePlan) return state;
    const lockedFields = new Set(current.scenePlan.lockedFields);
    if (lockedFields.has(field)) lockedFields.delete(field);
    else lockedFields.add(field);
    return { byAnimationId: { ...state.byAnimationId, [animationId]: {
      ...current,
      scenePlan: { ...current.scenePlan, lockedFields: [...lockedFields] },
    } } };
  }),
  syncEditorContext: (props, effects, cameraKeyframes, durations, activeAnimationId, cameraEnabled, cameraAutoGenerated) => set((state) => {
    let changed = false;
    const byAnimationId = { ...state.byAnimationId };
    for (const [id, entry] of Object.entries(state.byAnimationId)) {
      if (!entry.scenePlan) continue;
      const plan = entry.scenePlan;
      const propIds = new Set(props.map((prop) => prop.id));
      const invalidTargetIds = new Set(entry.segments.flatMap((segment) => segment.targetPropId && !propIds.has(segment.targetPropId) ? [segment.targetPropId] : []));
      if (plan.target.propId && !propIds.has(plan.target.propId)) invalidTargetIds.add(plan.target.propId);
      const nextSegments = entry.segments.map((segment) => {
        if (!segment.targetPropId || propIds.has(segment.targetPropId)) return segment;
        const unbound = { ...segment };
        delete unbound.targetPropId;
        return unbound;
      });
      const currentContacts = entry.contacts ?? plan.contacts;
      currentContacts.forEach((contact) => {
        if (contact.propId !== 'ground' && !propIds.has(contact.propId)) invalidTargetIds.add(contact.propId);
      });
      const nextContacts = currentContacts.filter((contact) => contact.propId === 'ground' || propIds.has(contact.propId));
      const nextTarget = { ...plan.target };
      if (nextTarget.propId && !propIds.has(nextTarget.propId)) {
        delete nextTarget.propId;
        delete nextTarget.distanceMeters;
        delete nextTarget.obstructed;
      }
      const nextCamera = activeAnimationId === undefined || activeAnimationId === id
        ? {
          ...plan.camera,
          keyframes: structuredClone(cameraKeyframes),
          ...(cameraEnabled === undefined ? {} : { enabled: cameraEnabled }),
          ...(cameraAutoGenerated === undefined ? {} : { autoGenerated: cameraAutoGenerated }),
        }
        : plan.camera;
      const nextProps = structuredClone(props);
      const nextEffects = structuredClone(effects.filter((event) => !event.animationId || event.animationId === id));
      const duration = durations[id] ?? plan.duration;
      const weapons = nextProps.filter((prop) => prop.kind === 'sword').map((prop) => ({ propId: prop.id, kind: 'sword' as const, attachedTo: prop.attachTo ?? null }));
      const warnings = [...new Set([
        ...(entry.warnings ?? []),
        ...(invalidTargetIds.size > 0 ? [`场景目标 ${[...invalidTargetIds].join('、')} 已移除；已清除动作、全局目标和接触中的失效引用，既有动作轨道未自动重生成，请重新规划并复查走位。`] : []),
      ])];
      if (JSON.stringify(plan.environment.props) === JSON.stringify(nextProps)
        && JSON.stringify(entry.segments) === JSON.stringify(nextSegments)
        && JSON.stringify(currentContacts) === JSON.stringify(nextContacts)
        && JSON.stringify(plan.target) === JSON.stringify(nextTarget)
        && JSON.stringify(entry.warnings ?? []) === JSON.stringify(warnings)
        && JSON.stringify(plan.effects) === JSON.stringify(nextEffects)
        && JSON.stringify(plan.camera) === JSON.stringify(nextCamera)
        && JSON.stringify(plan.weapons) === JSON.stringify(weapons)
        && plan.duration === duration) continue;
      byAnimationId[id] = { ...entry, segments: structuredClone(nextSegments), contacts: structuredClone(nextContacts), warnings, scenePlan: {
        ...plan,
        duration,
        environment: { props: nextProps },
        actions: structuredClone(nextSegments),
        contacts: structuredClone(nextContacts),
        target: nextTarget,
        weapons,
        effects: nextEffects,
        camera: structuredClone(nextCamera),
      } };
      changed = true;
    }
    return changed ? { byAnimationId } : state;
  }),
  replaceAll: (data) => set({ byAnimationId: structuredClone(data) }),
  clear: () => set({ byAnimationId: {} }),
}));
